### ISSUE TITLE
Community Member Score tables should list the sum of all of a user's voted-on-comments

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1010]
This should go under a column called "Total Upvotes"

**Comment by RomanGalochkin** [comment]
@OAGr Do we want to see votes for users comments? Either user`s votes for somebody?

**Comment by OAGr** [comment]
I'm not sure what you are asking exactly.

There are (A) votes that you get, and (B) votes that you give. For this, we're just interested in (A).

**Comment by OAGr** [comment]
like, _my_ "Total Votes" amount would be the sum of all of the votes on _my_ comments that others have given _me_.

**Comment by RomanGalochkin** [comment]
(A), ok.
