### ISSUE TITLE
Deploy Estiband to Github Pages

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1058]
I couldn't quite figure out how to deploy Estiband to Github pages. It would be nice if this were done automatically with updates to master; perhaps using Github actions to build.

I attempted to add commands for ``yarn run deploy`` to do this, but it didn't seem to run the app at https://foretold-app.github.io/estiband/

Don't spend more than 2 hours on this.

https://github.com/foretold-app/estiband

**Comment by RomanGalochkin** [comment]
I think for this I should be an admin. At least I did not have the luck with it.

**Comment by OAGr** [comment]
I didn't have much luck with it. At least I know it's not just me. Don't worry about it then, it's not very important at this point.
