### ISSUE TITLE
CdfChart: Figure out how to show dates on x-axis

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1075]
I'm not sure what the best way of doing this is.

I'd like to submit a CDF with some metadata on what dates points correspond to, and have the X-axis in these cases be dates instead of point values.

There are two things to figure out. The format, and also the optional D3 axes change.

**Comment by OAGr** [comment]
Please implement this as part of this story:

**Comment by RomanGalochkin** [comment]
What should I do here exactly?

**Comment by OAGr** [comment]
I think this was done in the other d3/dates story, ignore.
