### ISSUE TITLE
Vega: Display multiple distributions at different time points with errorBands with Vega

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1076]
https://vega.github.io/editor/#/examples/vega-lite/layer_line_errorband_ci

![image](https://user-images.githubusercontent.com/377065/74485537-e321a680-4eb2-11ea-9d27-514423e2b290.png)

In the components package, try to import Vega (not vega-light, preferably). Replicate the above chart, in Vega.

Try to make a React component that takes in a list of 2-50 CDFs along with timestamps in some format, and convert that into a graph like this. The bars should refer to the 5th and 95th percentiles, and the line should refer to the 50th percentile.

This will be used to show distributions that change over time.

Do this in a new page in the Showcase list.

**Comment by RomanGalochkin** [comment]
Interesting thing: https://vega.github.io/editor/#/examples/vega/budget-forecasts
![Screenshot_20200217_135123](https://user-images.githubusercontent.com/16107421/74647364-9678ec80-518c-11ea-8093-1217fc820830.png)

**Comment by OAGr** [comment]
Yea, I noticed. It's pretty neat, but would be tricky to fit to our work at this point in time.
