### ISSUE TITLE
UX: want some way to know how much probability I'm placing on certain outcomes

### ISSUE THREAD

**Issue by brachbach** [foretold-app/foretold#1094]
(meta: I'm assuming that you want random UX user feedback reported here, happy to keep to myself or share elsewhere if not)

I'd like to know more about how much probability I'm placing on various outcomes when I specify my distribution.

I think mostly I just want a graph of the cdf, also feels vaguely helpful to have density/unit for the PDF

right now I'm using r to quickly graph this up:

```
mean <- 2
se <- 10
xmin <- mean - 2 * se
xmax <- mean + 2 * se

set.seed(3000)
xseq<-seq(xmin, xmax,.01)
densities<-dnorm(xseq, mean, se)
cumulative<-pnorm(xseq, mean, se)
 
par(mfrow=c(1,2))

plot(xseq, densities, col="darkgreen",xlab="", ylab="Density", type="l",lwd=2, cex=2, main="PDF", cex.axis=.8)

plot(xseq, cumulative, col="darkorange", xlab="", ylab="Cumulative Probability",type="l",lwd=2, cex=2, main="CDF", cex.axis=.8)
```
<img width="719" alt="Screen Shot 2020-02-27 at 3 40 13 PM" src="https://user-images.githubusercontent.com/16952006/75496947-8248a280-5977-11ea-8795-76a3ba4b1a00.png">

**Comment by brachbach** [comment]
BTW this was in the context of predicting a stock price: https://www.foretold.io/c/2a6f08ab-6471-48e2-9cfd-7e398b93f8a0/m/8e695bfb-1401-4170-8a97-428c3ae5f6d0

**Comment by OAGr** [comment]
Thanks for the feedback! Very happy to get UX thoughts. 

I'm definitely interested in ways of improving this, it has more work to do.

**Comment by brachbach** [comment]
BTW this would be particularly helpful for lognormal distributions, since it's unintuitive to play around with them via mean and standard error, i.e. the Foretold `4 to 50` thing is super helpful with them

Is there some easy way to replicate the `4 to 50` thing in R or somewhere else where I can see the PDF and CDF?

**Comment by OAGr** [comment]
Try this tool (sorry it doesn't have ssl yet, fixing that)
https://www.highlyspeculativeestimates.com/dist-builder

If you enter the string there, you can see the pdf&cdf on top. You can also change the x or y axes to use a linear or log scaling, grow/shrink them, and add additional views below (with the "Add" button).

**Comment by OAGr** [comment]
It would be fairly to export the dists as vectors of x-y coordinates, which is how they are stored. Would this be useful to you, in R or Python? I'm not sure how easy it is to natively treat arbitrary shapes as distributions in them.

**Comment by OAGr** [comment]
If you click "stats" and hover over an area, you could see a few things about that point. 

Also, if there are other improvements / changes you'd like to see to that interface, definitely let me know. I've been spending the last few weeks on it, basically (well, most were on getting mixed distributions to work).

**Comment by brachbach** [comment]
hmm, if I try to go to https://www.highlyspeculativeestimates.com/dist-builder, I get `DNS_PROBE_FINISHED_NXDOMAIN`

do I need to do something special to get around the lack of SSL?

**Comment by OAGr** [comment]
Sorry about that, try this:
https://distracted-mirzakhani-b102f4.netlify.com/

The domain issues are being figured out now.

**Comment by OAGr** [comment]
Ok, now, 
https://www.highlyspeculativeestimates.com/dist-builder
should work.

Let me know how you find it. It's still decently rough, but hopefully a good path to continue with.
