### ISSUE TITLE
(Not sure if bug or confusing UX) scores not showing up

### ISSUE THREAD

**Issue by brachbach** [foretold-app/foretold#1096]
https://www.foretold.io/c/2a6f08ab-6471-48e2-9cfd-7e398b93f8a0/m/8e695bfb-1401-4170-8a97-428c3ae5f6d0
<img width="1869" alt="Screen Shot 2020-02-27 at 3 50 31 PM" src="https://user-images.githubusercontent.com/16952006/75497378-e9b32200-5978-11ea-94c7-d6d9841cc267.png">
<img width="1861" alt="Screen Shot 2020-02-27 at 3 50 24 PM" src="https://user-images.githubusercontent.com/16952006/75497379-ea4bb880-5978-11ea-8c6a-f33d8435fc7c.png">

**Comment by OAGr** [comment]
This is a bug, thanks for reporting!
