### ISSUE TITLE
Estiband: D3: Only-discrete distributions are broken again

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1103]
Example input:
floor(20,30)

![image](https://user-images.githubusercontent.com/377065/75792385-cec02380-5d65-11ea-8567-c4042c640fa8.png)

**Comment by RomanGalochkin** [comment]
I think this issue was solved in the https://github.com/foretold-app/estiband/pull/16. When I enter this input the error "Correct Guesstimator string input to show distribution." is shown. That means that DistPlusIngredients.toDistPlus does not return distribution.

**Comment by OAGr** [comment]
Sorry, try it with this input:
```floor(20 to 30)```

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/75869410-6cb4fc00-5e01-11ea-8c4f-86fd4656ab83.png)

This is what I see

**Comment by RomanGalochkin** [comment]
Got it, thanks.
