### ISSUE TITLE
WideDomain: Implement "mean()" function for continuous, discrete, mixed distributions

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1116]
In the file Distributions.re, continuous, discrete, and mixed distributions should all have a mean() function that returns their distribution's mean. 

Continuous distribution's means should be different when they are Stepwise vs. Linear.

**Comment by RomanGalochkin** [comment]
I understood that I do not understand this field properly as I should before writing code. I support that the mean/variances could be found through jstat.man/variance. So I will leave these issues to professionals.

**Comment by OAGr** [comment]
That's fine, just leave this for now then.

**Comment by NunoSempere** [comment]
I can do this.

**Comment by OAGr** [comment]
That sounds great. I suggest writing a few tests for this. Let me know if you have any questions.
