### ISSUE TITLE
Foretold: Some pages on master breaking in prod:

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1124]
https://prediction-backend-staging.herokuapp.com/c/7da809bb-d697-40e6-afa4-8f473594045c

I originally thought that this was from an error with Auth0, but it seems that error was unrelated. 

This will be tricky to debug, as it seems to be a javascript error. Maybe you can push a version to Heroku/master with the sourcemaps for debugging there, or try building the production version locally.

Most pages are fine. Interestingly, some community pages work, but most don't.
https://prediction-backend-staging.herokuapp.com/c/54d76d9a-e465-4b27-8691-25d167bb4ec7
That works.

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/78506164-afa32000-776f-11ea-87cc-411bc4a11893.png)

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/78506190-db260a80-776f-11ea-8a0b-8404b9a3f3e1.png)

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/78506234-293b0e00-7770-11ea-93a9-cacb2b2c62d0.png)

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/78506470-98653200-7771-11ea-8aa5-f9c1e08e53e9.png)

{
  "body": {},
  "qs": {
    "client_id": "oIh53ohBnA4xqhaO8vZXa7PiW6TCXjMV",
    "response_type": "token id_token",
    "redirect_uri": "https://prediction-backend-staging.herokuapp.com/callback",
    "scope": "openid email profile",
    "state": "-OOvo9nLgg5gKzbPny9VjNzY-eubr1sp",
    "nonce": "oaoyjSd6e2AxXsTn2UDAk9kPqaGQK2lq",
    "response_mode": "web_message",
    "prompt": "none",
    "auth0Client": "eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS4xMS4zIn0="
  },
  "connection": null,
  "error": {
    "message": "The specified redirect_uri 'https://prediction-backend-staging.herokuapp.com/callback' does not have a registered origin.",
    "oauthError": "invalid_request",
    "type": "request-error"
  },
  "session_id": "tGnRn_bf7YJKpePGOckaK_AUV5bMFQPP",
  "session_connection": "google-oauth2"
}

**Comment by RomanGalochkin** [comment]
Ok, thanks for extended data.
