### ISSUE TITLE
Bots are not able to get measurements from private channels

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#1136]

**Comment by OAGr** [comment]
My impression was that admin bots / bots from admin users could get measurements from private channels?

**Comment by OAGr** [comment]
Does this mean that no bots could get measurements from private channels, even ones with users that have permission?

**Comment by RomanGalochkin** [comment]
Yes, bots do not have access to measurements from channels even where its owners are in those channels.

**Comment by OAGr** [comment]
Yep, that's definitely a bug then. That said, I haven't heard anyone request this yet, so it's less urgent than other things.

**Comment by RomanGalochkin** [comment]
Sure. But it is interesting how could not we notice this before.

**Comment by OAGr** [comment]
Definitely, thanks for filing!
