### ISSUE TITLE
Foretold Client: Screenshot of source-map-explorer

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1139]
Same as the widedomain work. There's a script for it but it didnt' work for me.

**Comment by RomanGalochkin** [comment]
![Screenshot_20200410_110813](https://user-images.githubusercontent.com/16107421/78974854-94436680-7b1b-11ea-8440-f4fdcfc7ecda.png)

**Comment by OAGr** [comment]
Thanks! What command did you run to make that?

**Comment by RomanGalochkin** [comment]
![Screenshot_20200410_111240](https://user-images.githubusercontent.com/16107421/78975160-319e9a80-7b1c-11ea-8d89-d16860a95835.png)

Try to run parcel builder, it should create a report as an HTML page.

**Comment by OAGr** [comment]
Thanks!
