### ISSUE TITLE
Foretold: Questions don't leave "pending resolution" with manual change

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1140]
From a user:

"Questions no longer leave the "pending resolution" section, even when the resolution date is later set to be in the future; e.g. my question on the next round of grants of the animal welfare fund is now "pending since in 25 days", since I changed the expected resolution date to 25 days in the future."

I haven't really tested this, so test it first and see if you could get it to fail.

**Comment by RomanGalochkin** [comment]
Could not reproduce.
