### ISSUE TITLE
Fix cdfLib issue with Observable

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1146]
https://observablehq.com/@oagr/guesstimator-library

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/79455741-3dd79b80-7fe5-11ea-9cfb-7bb7a8b7a7da.png)

**Comment by NunoSempere** [comment]
Fixed the problem by going back to foretold/cdf@1 from npm. Made a pull request on observable; https://observablehq.com/@nunosempere/guesstimator-library

**Comment by OAGr** [comment]
That works, thanks. I imagine we'll later want to update this, but that would be a separate story.
