### ISSUE TITLE
Make a bash script to copy code from Components to Client

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1162]
It seems possible that keeping the Components separate is causing a lot of issues. Try merging it. This may be a bit tricky. See if merging makes bsb:watch better. 

It's possible there could be other solutions as well. For instance, instead of loading bs-css in both client and Components, just do it in Components, then call that bs-css in the client. Try this too, perhaps before or after, if the first doesn't succeed

**Comment by RomanGalochkin** [comment]
Done in https://github.com/foretold-app/foretold/issues/1154, see "bs-fixer.sh" file.
