### ISSUE TITLE
Question - How do I write a new notebook? 

### ISSUE THREAD

**Issue by edoarad** [foretold-app/foretold#1167]
Is there a documentation for that?

**Comment by OAGr** [comment]
There's no documentation yet. You edit the main part with Markdown. Tables in notebooks are more tricky and currently require custom tooling that takes some time to use. We're working on making this workflow easier.

Can you describe a bit of what you are interested in doing with workflows, when, and how comfortable you are with coding/scripting, if at all?

**Comment by edoarad** [comment]
I'm comfortable with coding, that shouldn't be a problem. 

I am running an intro forecasting workshop next week, and I thought that it might be great to have people directly experimenting on a notebook (which if works could also serve as a nice introductory material in general). Something designed a bit like Jacob's [Beyond the Hill](https://www.foretold.io/c/1bea107b-6a7f-4f39-a599-0a2d285ae101/n/5ceba5ae-60fc-4bd3-93aa-eeb333a15464) could be amazing. 

I could alternatively just open a set of questions, but that has a few problems. It would be more difficult to communicate and make sure that no one is having tech issues, and it would be harder as a stand alone template.

So if you have alternative suggestions it would be great. 
I just realized that I can copy the Markdown script of Jacob's notebook, so that shouldn't be so hard for me to figure out how to work with it. Curious to hear your comments/suggestions regardless :)

**Comment by edoarad** [comment]
Ok, [got it](https://www.foretold.io/c/a30a859c-2131-4703-9368-2f7c7372fdd4/n/48f6e50a-68d9-4fe6-a8f2-27d5a627dc66) 😊

**Comment by edoarad** [comment]
People would need to refresh the page to see what the others are doing, so that would make it less entertaining. Also signing up might be a chore, even though it's pretty easy and doesn't actually require email verification. Getting off topic though..

**Comment by OAGr** [comment]
Good to see! 

Yes, notebooks become primarily messy if you wanted big tables of predictions (this either requires some scripts to create the questions and generate the tables, or a lot of manual time).  If you only want a few and want to organize them in that way,  then you just use the ForetoldJs blocks as used in that document. 

You are definitely right that currently the app does not support live updates.  I played with the system for a while to do refreshes every 30 seconds,  but this did become a bit annoying.  I think doing a good job at this would take quite a while,  and is quite different from the regular use case, where users are typically a few hours apart from each other.

Signing up on any website is a bit of a chore.  I tried making it pretty simple.  These people are free to use bogus email addresses of the want of course, which I really hope is not that difficult.

Good luck with the forecasting workshop!

**Comment by edoarad** [comment]
Thanks!

**Comment by edoarad** [comment]
Hi @OAGr , letting you know that the notebook is mostly done if you want to take a look :) I'm running the workshop in two days from now, and I'm very curious to see how this is gonna go. 

https://www.foretold.io/c/a30a859c-2131-4703-9368-2f7c7372fdd4/n/48f6e50a-68d9-4fe6-a8f2-27d5a627dc66

**Comment by OAGr** [comment]
That looks really nice! I may suggest adding some touch-ups after the presentation and releasing it for casual readers who can't attend, similar to the over the hill essay from Jacob. 
https://www.foretold.io/c/1bea107b-6a7f-4f39-a599-0a2d285ae101/n/5ceba5ae-60fc-4bd3-93aa-eeb333a15464
