### ISSUE TITLE
Lots of "does not have a registered origin" errors in auth0

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1171]

**Comment by OAGr** [comment]
https://manage.auth0.com/dashboard/us/foretold/logs

I'm not sure if this is actually causing issues. I tried adding the right origin, but it's still causing errors.

**Comment by RomanGalochkin** [comment]
Could you provide a screen? It seems like I do not have access to the project on auth.com.

**Comment by OAGr** [comment]
I sent the info via Slack
