### ISSUE TITLE
Measurable Form Fixes

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#137]
Edit ``MeasurableForm.re``.

1) The form should use the new ``ReFormNext`` instead of ``ReForm``. See ``BotCreate.re``. Demo here: https://github.com/Astrocoders/reform/blob/49b4a867d99b8e318201f07edf9e6e752c1d8b61/packages/example/src/PostAddNext.re
(You can use lenses or not)

2) The type of "Specific Date in Name" should be option(MomentRe.Moment.t) or (option(string)) or similar. When it is None, the specific date should be empty. "Xing" the date should set it back to None.

3) Move the "Submit" Button on bottom to align with other questions.
See: https://ant.design/components/form/

![image](https://user-images.githubusercontent.com/377065/56468880-38735f80-642a-11e9-8729-c6bb3b6bca04.png)

**Comment by OAGr** [comment]
@GalochkinKirov what is the status of this now?

**Comment by RomanGalochkin** [comment]
I think it was not ready, should figure it out.
