### ISSUE TITLE
Measurable Queries should have field for ``lastMeasurementByAgent`` or similar

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#22]
It's often really useful to get the last measurement by the logged in user, as well as that for what will essentially be the aggregator, with the other information.

**Comment by GalochkinKirov** [comment]
@OAGr Did not get this issue clearly

**Comment by GalochkinKirov** [comment]
lastMeasurementByAgent will be argument of Measurable query or field of Measurable?

**Comment by OAGr** [comment]
Actually, let's pause this.

**Comment by OAGr** [comment]
So, basically, this is what we want:
For each measurable, we will eventually want two previous measurements:
- The last measurement of the current user, so they could see what they have most recently estimated.
- The last estimate of a specific bot, who will be adding an aggregate for what it thinks the answer is.

Would you have ideas on the best way to do this?

**Comment by OAGr** [comment]
This has become relevant again, now that we have the aggregationBot setup.

It's for this bit:

![image](https://user-images.githubusercontent.com/377065/56968703-90f9d980-6b5b-11e9-9578-65d0fd25b508.png)
