### ISSUE TITLE
Move "Guesstimator" library from /packages/client into it's own package

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#255]
This will be used in the "Components" library shortly after.

It's package should be named "guesstimator"

Also, spend some time cleaning up the interface. Spend up to 2 days on this.

**Comment by OAGr** [comment]
It should be possible to later import the library into Guesstimate, where it originally came from.

https://github.com/getguesstimate/guesstimate-app

**Comment by RomanGalochkin** [comment]
Move the package - 1 SP I think, interfaces - another deal.
