### ISSUE TITLE
Entering a log normal distribution

### ISSUE THREAD

**Issue by Jsevillamol** [foretold-app/foretold#287]
I tried entering a lognormal distribution as "1 to 80000". In the input page the distribution looked fine (albeit the scaling choice was unusual, showing values up to 10^9) but after submitting it the distribution looks all wrong, extending into the negative numbers.

![image](https://user-images.githubusercontent.com/5825805/59629263-b90cbe80-9142-11e9-8f05-f25f7aab6a11.png)

**Comment by OAGr** [comment]
This is an issue with smoothing. I'm not sure what the best way is of solving it, may allow users to choose smoothing levels.

**Comment by OAGr** [comment]
I spent a bit of time smoothing this. We're also adding the ability to truncate values at mins/maxs for all predictions in specific questions. I also added a warning flag for lognormals with that much width (it's pretty messy in terms of smoothing)

**Comment by RomanGalochkin** [comment]
I think that the issue is corresponding with Node.js integers supports. https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin

**Comment by OAGr** [comment]
Interesting, good find.

**Comment by OAGr** [comment]
This is still an issue.

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/377065/63135412-b35a1a80-bfc5-11e9-9812-56e541f9e5b5.png">

The way to fix it isn't with cut-offs. I think it's a nasty stats issue, so only fix it (or part of it) if you can do so quickly, or are quite sure you understand how. Else, I'll have on of the stats people do it.

**Comment by RomanGalochkin** [comment]
Well, I really don't know how to fix it since it is a stats issue. But when I read description of "pdfast" it said that edges are done with some random way. It is strange to know that it is random because we pass particular input values every time and should get always the same results. 

> min: min value for the pdf's x range. If resulting pdf won't fit, the pdf's left part will be squeezed, as described here. Defaults to smallest value in the array minus some threshold.
> max: max value for the pdf's x range. If resulting pdf won't fit, the pdf's right will be squeezed. Defaults to largest value in the array plus some threshold.

The main words here are "Defaults to smallest value in the array minus some threshold". 

Links:
- https://www.npmjs.com/package/pdfast
- https://en.wikipedia.org/wiki/Kernel_density_estimation

I assume that there is another lib to get KDE of data samples.

**Comment by RomanGalochkin** [comment]
Or may be random edges are right for this case?

**Comment by OAGr** [comment]
Good point. I'm not sure. I'll get a stats person to look at this.
