### ISSUE TITLE
Upgrade dependencies to fix Github Security Alerts

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#399]
See a private message on what exactly these are. Use your judgement in deciding if some may not be relevant.

**Comment by RomanGalochkin** [comment]
@OAGr Could you give a small explanation how to find "Github Security Alerts"?

**Comment by OAGr** [comment]
I think I sent a message in slack with screenshots. My guess is that you don't have access because of access privileges. 

![image](https://user-images.githubusercontent.com/377065/61939250-c19ab500-af8a-11e9-8c42-2cfe912b4d9f.png)
