### ISSUE TITLE
Client: refactoring the names of components

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#422]
Should we rename these components using shorter names?

![Screenshot_20190726_090852](https://user-images.githubusercontent.com/16107421/61929897-015e9e00-af85-11e9-811b-daa88d0bda84.png)

**Comment by OAGr** [comment]
Hm... this naming system is lengthy, but deliberate. The issue with OCaml is that no two files could have the same name, so we need to organize things somehow. We may not need the "Foretold" name in the beginning though.

I'd like to look into this more (and suggest you do to). Other libraries seem to be doing similar things.
https://github.com/Astrocoders/reform/tree/master/packages/bs-reform/src

Here's a page on recommended practices I just found that seems interesting. https://dev.to/yawaramin/bucklescript-best-practice-public-and-private-modules-5ald

**Comment by RomanGalochkin** [comment]
I think there is no "name" collisions at the moment.

**Comment by OAGr** [comment]
There could be in the future. Lots seem really generic, like "Series"; how do we make it obvious it's the Series Component instead of a Series data model or similar?

**Comment by RomanGalochkin** [comment]
Yes sure, we should use prefixes but not long like "Foretold__Components__Measurement__Form", just "MeasurementForm"?

**Comment by OAGr** [comment]
What would you do with names like Foretold__Components__Series? Most like that are pretty generic.

**Comment by RomanGalochkin** [comment]
Foretold__Component__StatusDisplay.re --> StatusDisplay.re
Foretold__Components.re ---> [x]
Foretold__Components__Channel.re --> Channel.re
Foretold__Components__Ken.re --> KenAdapter.re (or similar)
Foretold__Components__Measurable.re --> Measurable.re
Foretold__Components__Measurable__FullPresentation.re --> MeasurablePage.re
Foretold__Components__Measurable__Items.re --> MeasurableItems.re
Foretold__Components__Measurables.re --> Measurables.re
Foretold__Components__Measurables__SeriesTable.re --> MeasurablesSeriesTable.re
Foretold__Components__Measurement__Form.re --> MeasurementsForm.re
Foretold__Components__Measurements.re --> MeasurementsCommon.re
Foretold__Components__Measurements__Table.re --> MeasurementsTable.re
Foretold__Components__Series.re --> Series.re
Foretold__Components__Series__Collection.re --> SeriesCollection.re
Foretold__Components__Shared.re --> Shared.re

And so on, how about this?

**Comment by OAGr** [comment]
It's still not obvious to me that Series means the component, it could mean a few things.

**Comment by RomanGalochkin** [comment]
I think that the name convention should be like:
1. Components: SeriesItem, SeriesIndex, SeriesCard, SeriesSearchBar and so on.
2. Functors: SeriesFunctor and so on.
3. Vendor specific components will have been named "FC_SeriesIndex" and so on.

But there is no reason to keep long names of files.
