### ISSUE TITLE
Make a list of UX bugs in application

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#426]
There are several. Spend 1-4 hours making a list of issues that should be fixed. 

Example: When you resolve a question, that isn't updated in the question index immediately.

**Comment by RomanGalochkin** [comment]
- Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

![Screenshot_20190730_111849](https://user-images.githubusercontent.com/16107421/62112662-ced1df80-b2bb-11e9-948d-1dcbec77bfb3.png)
