### ISSUE TITLE
Figure out: Load KEN async, via github

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#427]
Right now Data.json is part of the main app, but it would be better if it could be loaded separately. This is data that will change frequently; and it would be nice if we didn't have to redeploy the application every time it changes.

One option would be to have it be part of a different Github repo, which would be deployed separately. This should update a CDN. Foretold should load information from this CDN, in order to load the data in Data.json. 

This task is to figure out a way to do this. Hopefully this would be relatively simple, cheap, and effective.

**Comment by RomanGalochkin** [comment]
Why just not use something like AWS S3, or GLP Storage? If everyone can edit this file yes better choice would be github, but is there a need to load it though cdn?

**Comment by OAGr** [comment]
We'd want to basically load the most recent github version into Foretold.io. My guess was that this would be easiest with some trigger; that whenever github is updated, it updates some CDN or S3 or similar. S3 would be fine. Then we make this static file public and import it directly from the app.

**Comment by OAGr** [comment]
Would there be a decent way of automatically updating S3 or similar, from Github? I know there are other systems (like npm) that basically act as cdns for github repos.

**Comment by RomanGalochkin** [comment]
1. To use github like this with another repo: 
https://raw.githubusercontent.com/OAGr/foretold/master/packages/client/src/Data.json

2. Google Cloud Platform + Google Storage (or with S3):
1. Set up trigger on github repo in "Cloud Build"
2. Set up builder to copy JSON on S3 or Google Storage (the better) 
see to better understand: https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts

**Comment by RomanGalochkin** [comment]
3. Or even something like this github --> AWS Pipeline --> S3 (interesting to try):
https://medium.com/@sithum/automate-static-website-deployment-from-github-to-s3-using-aws-codepipeline-16acca25ebc1

**Comment by RomanGalochkin** [comment]
4. AWS Lambdas, Google Functions (https://cloud.google.com/functions/) as hooks on github and then copy the file on S3, or Google Storage.

**Comment by RomanGalochkin** [comment]
@OAGr

**Comment by OAGr** [comment]
Hm... I'd probably prefer that we stay with just AWS, instead of having some things in aws and some in Google Cloud. 

Do you think we could use this easily? Maybe it would be simpler / easier?
https://deploybot.com/#pricing

Other ideas here:
https://stackoverflow.com/questions/32530352/best-strategy-to-deploy-static-site-to-s3-on-github-push

**Comment by RomanGalochkin** [comment]
It is not easy I think, instead, this is not reliable more then AWS:
https://deploybot.com/#pricing

On the Internet there are so many solutions, but some of them only for a day.

Even our team has similar solution (deployment pipeline, beta version now still). But for Foretold I want to propose something more reliable.

**Comment by OAGr** [comment]
Sounds good. Can you make a new story for that, done correctly with s3?

**Comment by OAGr** [comment]
@RomanGalochkin Now that I think about it, what would you think about doing it via the server?

The server subscribes to a Github repo. Whenever that changes, the server would then fetch the information and save it to the database, or to a static file, or to s3. Then the server would send this info to the client on behalf of the graphQL api. 

I'm hesitant to use much of AWS and similar; in part to eliminate external dependencies. Also, in the future, I am imagining that communities will want their own knowledge bases, so this could be a good step to getting there.

**Comment by RomanGalochkin** [comment]
Ok, in this case we should do this:
1. github repo with "data.json" file
2. set address and access token to this repo in application settings
3. logic to subscribe on GitHub hooks
4. logic to update Data.json file (store in local storage or in S3, or even in DB)

Btw storing Data.json file right on the server is a bad idea since we will have to set volumes for application (Docker Compose, Heroku).

**Comment by OAGr** [comment]
Sounds good. Do you have thoughts on if we should use s3 or db? My intuition would be the db, for simplicity, at this point, especially if we want it to go through our server's API (via graphql) anyway.

**Comment by OAGr** [comment]
test comment

**Comment by RomanGalochkin** [comment]
Yes DB is not bad solution, I too do not want to increase external dependencies.

**Comment by OAGr** [comment]
Ok, can you write stories for this? If it's more than 2, it can be an epic.

**Comment by OAGr** [comment]
Actually, I just did this, please review if those are adequate / what their points should be.

**Comment by RomanGalochkin** [comment]
ok, sure
