### ISSUE TITLE
Refactoring: component usage

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#435]
![Screenshot_20190731_083707](https://user-images.githubusercontent.com/16107421/62186278-63951580-b36e-11e9-8acf-fdcf638599bf.png)

Refactoring usages of components everywhere you are able to find this. Do like on the screen.

**Comment by OAGr** [comment]
Have you considered using or trying hooks instead? It seems like that may be the best way of handling some of this kind of stuff.

**Comment by RomanGalochkin** [comment]
Hooks is good idea, but I think it will be on the next stages of app.

**Comment by OAGr** [comment]
Makes sense.

Why is this change being made? I could go both ways.

**Comment by RomanGalochkin** [comment]
You mean why we should write component usages like this: "<componentname />". Because it is more readable and intuitively then "pipes" of RML.

**Comment by OAGr** [comment]
Hm... I don't find this myself. How important is this to you?

**Comment by RomanGalochkin** [comment]
It is not important of course for me, but will help sometimes.
