### ISSUE TITLE
Auth0 & Foretold Integration: users should have "verified" emails

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#436]
Either show a special "message" to users or may it be redirect them into "Auth0" page.

**Comment by OAGr** [comment]
Can you describe this more? Like, if their emails aren't verified, what would happen? Would there be a link to "send a new confirmation email" or similar?

**Comment by RomanGalochkin** [comment]
We should make users to verify theirs emails with Auth0, because we send emails and we do not want to be spamers.

May it would help:
https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

**Comment by OAGr** [comment]
I meant, can you describe the functionality more? 

How about this:
For users without verified emails, we'll show a simple message in the header. It will say,
"Please verify your email address. Click here to send a new verification email."

Clicking there will trigger a mutation which will trigger auth0 to send a new verification email. 

On success of that mutation, the message will be replaced with one that reads, "Email sent"

**Comment by RomanGalochkin** [comment]
Yes, good logic
