### ISSUE TITLE
Auth by "one-time token"

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#437]
When you go to "http://localhost:1234/agents/bff853aa-b474-4273-9b25-366939e47d76#token=472d32f1067f4b47f5f60c4fde4f230cbf67c495b633427045ad21520a6245f8%5C" it will always show the message about "You are being redirected...".

**Comment by OAGr** [comment]
It redirects pretty quickly for me. Happy for it to be investigated though.
