### ISSUE TITLE
Title of entities shown as empty string in emails

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#443]
I just got an email with subject: 

> Question "" is changed

For the question: 

> The Prediction Pyramid Karmaon 08/01/2019

Where "The Prediction Pyramid" and "Karma" are both entities. 

![image](https://user-images.githubusercontent.com/21347592/62318044-398d4180-b49b-11e9-8bfc-4129afaf367d.png)

**Comment by OAGr** [comment]
I imagine this will be tricky, as it will require KEN on the server. Another temporary way could be to save the KEN names on the client.

**Comment by RomanGalochkin** [comment]
ok, will review in some minutes

**Comment by RomanGalochkin** [comment]
@OAGr Really do not have any idea how to make it in simplest way

**Comment by RomanGalochkin** [comment]
Why we are not able to save names when create measurables? Why are they dynamic?

**Comment by OAGr** [comment]
They're dynamic because they're references to entities, who's names can change. That said, we could save this data just for reference and the server for now.

**Comment by OAGr** [comment]
Will put this on hold for a bit, need to think through how to do this.

**Comment by OAGr** [comment]
How about this: We just save the entity names, with the measurable name, when the measurable is created? More specifically, we make a new field on Measurable called, "RenderedName" or similar, and that includes the names of the entities, but it's saved that way on the client.

**Comment by OAGr** [comment]
@RomanGalochkin

**Comment by RomanGalochkin** [comment]
Good point. So we are going to have two columns with names, first would be empty and the second one would be with Entity name? Or first with name and second is empty. May be does it have a sense to aggregate Entities names on the server side always? Or we want to give any client to use their own Entities names?

**Comment by OAGr** [comment]
"So we are going to have two columns with names, first would be empty and the second one would be with Entity name?"
-> Yep. The second one will only be used on the server, first only used on the client.

" May be does it have a sense to aggregate Entities names on the server side always? "
-> Yes, but not yet. That will get a bit messy, especially when Ken gets updated via S3, so we'll do that later.

**Comment by OAGr** [comment]
Actually, this wouldn't support questions created by Bots, which may happen soon. Gr...

**Comment by RomanGalochkin** [comment]
Anyway the pattern which we need to apply in this case called "One Source Of Truth". May be we are storing "json" on server side and giving it to the clients, may be there will be S3 or similar. Need to think it over later.

**Comment by RomanGalochkin** [comment]
It seems that now we are ready to go on with this issue?

**Comment by OAGr** [comment]
I feel like the ideal solution would be to lead KEN in the server, and have it load the names as needed. Does this seem doable to you? It's definitely some work.

**Comment by RomanGalochkin** [comment]
Yes, I agree this would be better to use KEN on the server side, sure. I think we are able to do it, if KEN is a library which is written on TS, RM or another language that is compiled to JS there should not be much problems. Feel that we need to do it anyway.

**Comment by OAGr** [comment]
Yea, that makes sense. You may have to modify Ken a bit to load it in the server. If this seems more than 2 points, let's move to an epic.

**Comment by OAGr** [comment]
Makes sense. How about you make a task to investigate the challenge of doing this? I assume it could take 1 story or multiple. 

Ken does have a small js library, as well as an ocaml library.

**Comment by RomanGalochkin** [comment]
@RomanGalochkin See https://kenstandard.com/ JS lib

**Comment by RomanGalochkin** [comment]
@OAGr Could you give an example of the usage of "ken js" lib? I have create the branch "feature/443" if it helps. See "packages/server/src/graphql/schema.js" file. Here are some code pieces:
```
      ken: {
        type: GraphQLJSON,
        resolve: async () => {
          const data = require('../data');
          const json = await data.globalSettings.getMain();
          const { entityGraph } = json;

          const ken = require('@foretold/ken-js/lib');

          return ken.main(entityGraph)
            .findThing('@lesswrong/posts/rain')
            .connectedPropertyThings();
        },
      },
```

**Comment by OAGr** [comment]
Hm... It depends on what you want to do. Here's the main relevant file/interface from the kenjs lib:
https://github.com/kenstandard/ken-js/blob/master/packages/ken-js/src/JS/index.js

The [Ken Explorer](https://explorer.kenstandard.com/) uses this interface, so you can go through it's code to see a bunch of examples. 
https://github.com/kenstandard/ken-js/blob/master/packages/ken-explorer/src/Home.js

```js
const transformedData = db.things().filter(t => t.propertyIdFacts(CONSTANTS.NAME).length > 0).map(t => {
  return {
    id: t.id(),
    name: <Value fact={t.propertyIdFacts(CONSTANTS.NAME)[0]}/>,
    instanceOf: <Value fact={t.propertyIdFacts(CONSTANTS.INSTANCE_OF)[0]}/>,
  }
});
```

That code you describe looks pretty good. One thing to note is that we generally just want the name of the item. You can see this done in [this file](https://github.com/kenstandard/ken-js/blob/master/packages/ken-explorer/src/Thing.js)

```js
const columns = connectedProperties.map(p => ({
    title: p.propertyIdFacts(CONSTANTS.NAME)[0].value().data(),
    dataIndex: 'fact',
    key: p.id(),
    render: (fact) => {
      return(<Value fact={fact.internalThing().propertyIdFacts(p.id())[0]}/>)
    }
  }))
```
Where,
```js
export const CONSTANTS = {
    NAME: "@base/properties/p-name",
    INSTANCE_OF: "@base/properties/p-instance-of"
}
```

I guess one messy thing about this is that there are these magic variables like NAME that need to be consistent on the client and the server, but right now that's fine.

**Comment by RomanGalochkin** [comment]
Oh, thanks, will use you tips.

**Comment by RomanGalochkin** [comment]
Ken-js library has a bug. But I do not understand how to fix it.

Data.json
```
[
  {
    "config": {
      "baseId": "base",
      "resourceId": "properties",
      "aliases": {}
    },
    "p-instance-of": {
      "p-name": "Instance of"
    },
    "p-description": {
      "p-name": "Description"
    }
  }
]
```

Test code:
```
const crypto = require('crypto');

global.crypto = {
  getRandomValues: function(buffer) {
    crypto.randomFill(buffer, function(err, buf){
      if (err) throw err;
    });
  }
};

setInterval(() => {
  const ken = require('./dist/index.js');
  const data = require('./data');
  const db = ken.main(data);

  console.log('DB things length is', db.things().length);
  console.log('DB directories length is', db.directories().length);
  console.log('DB rootDirectories length is', db.rootDirectories().length);
  console.log('DB facts length', db.json().facts.length);
  console.log('DB things length', db.json().things.length);
}, 1000);
```

Results always are not predictable:
> DB things length is 4
> DB directories length is 2
> DB rootDirectories length is 1
> DB facts length 1
> DB things length 4

> DB things length is 5
> DB directories length is 2
> DB rootDirectories length is 1
> DB facts length 2
> DB things length 5

The bigger a data file is then bigger the error dispersion is.

So to use this code on the server side we have to fix it. Since it is not working.

**Comment by RomanGalochkin** [comment]
Oh, may it be it is because of random IDs of things/facts. Because there is used unique filler everywhere.

**Comment by RomanGalochkin** [comment]
Yes, I was right. Will fix.

**Comment by RomanGalochkin** [comment]
@OAGr If there is ability to give me an access to make branches to this repository (https://github.com/kenstandard/ken-js) please do, I want to make PR.

**Comment by OAGr** [comment]
Done, try it now

**Comment by RomanGalochkin** [comment]
Hm, still cannot push to the repo.

**Comment by RomanGalochkin** [comment]
Ok now

**Comment by OAGr** [comment]
Cool

**Comment by RomanGalochkin** [comment]
Could you publish new "bs-ken" 0.0.6 version?
https://github.com/kenstandard/ken-js/pulls

To use this version it is necessary to publish the package first in npm repo.

**Comment by OAGr** [comment]
Sure, 2min

**Comment by RomanGalochkin** [comment]
Thanks.
