### ISSUE TITLE
[Bot]: Auto-resolving is not working

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#461]

**Comment by OAGr** [comment]
Can you describe what this means? I have no idea, really.

**Comment by RomanGalochkin** [comment]
I have found that there is no bots or something else in the application to resolve Measurables which need to be "resolved after expected resolution date"

**Comment by OAGr** [comment]
Ok, makes sense

**Comment by OAGr** [comment]
Maybe we could change the name to something like: "Bug: Auto-resolving is not working"?
