### ISSUE TITLE
Consider: How difficult/ok would it be to move templates to code?

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#467]
Right now they are saved in the database. Hypothetically this could be easier if there were admins who used this, but for the next several years this aspect probably won't change much. It could be quite a bit simpler just to have this in the code, and change it via the server. 

Please do a small amount of investigation, and say:
1) How difficult would this be to change (number of points, maybe)
2) How reasonable do you think it is? Is there any easy way to edit the db things, or are you expecting that we'll have a nice admin panel set up?

**Comment by RomanGalochkin** [comment]
1) 1-3 not more.
2) The main idea of templates it to edit this in DB without touching code base and deployment staff. Yes, every our project had something like a Control Panel. Anyway, we can set up any panel (https://github.com/admin-interface/admin-interface/, http://simov.github.io/express-admin/ or similar) to edit this tables, without writing Control Panel, it would be quite the same. Or if it matters to use pgAdmin within Docker Compose. *Or may be add a mutation to edit Templates thought graphql?*

**Comment by RomanGalochkin** [comment]
@OAGr For an experiment I have done it in the next PR, so I feel that is more comfortable. I did not remove any tables or code, just replace some interfaces.
