### ISSUE TITLE
[Server]: Notification Subsystem Improvements

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#473]
Adds columns:
"attemptCounter"
"errorAt"
"errorReason" (enum: INTERTAL_ERROR, EXTERNAL_ERROR, PREFERENCES_ERROR, EMAIL_ADDRESS_ERROR)

When Application cannot send notification let it add one to "attemptCounter" and set "errorAt", "errorReason". On the next circle it should pass notification with "attemptCounter" >= 3.

**Comment by OAGr** [comment]
Oh, good idea. Can it also log the error, as, "Error text" or similar?

**Comment by RomanGalochkin** [comment]
sure
