### ISSUE TITLE
Description of Min/Max in question creator

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#476]
Some new users entered the actual lower and upper bounds for their predictions in the "Min" and "Max" fields, and thought that's how they made a new prediction. (As opposed to realising this was just where they entered the min and max for everyone else's predictions.)

Would be good to add something like:

`<Form.Item label="Min" help="What are the most extreme values this could possibly take? For example, inches of rain tomorrow has a minimum of 0.">`

Though don't know if this will mess up since there are two items in a row.

**Comment by OAGr** [comment]
I like this, though also unsure about doing so with the form system. If you could make a quick wireframe, @RomanGalochkin could probably give it a go.

**Comment by OAGr** [comment]
Maybe there's a section for "Bounds", that has the help text underneath it. Min/max would be underneath.
