### ISSUE TITLE
[Sever] Adds Google StackDrive to catch production errors

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#481]
Google StackDriver is a free tool to catch production errors, I think we should use this.

**Comment by OAGr** [comment]
Are there any other apps we could use for this instead? I know Heroku has a setup with several options. Google Stackdriver would require us getting set up with the Google Stack.

**Comment by OAGr** [comment]
@RomanGalochkin

**Comment by RomanGalochkin** [comment]
Anyway there will be something external I assume. 

- Heroku uses "Airbrake" add-on (it is free only for first steps)
- Google Stack (free, prefer this)
- Custom simple solution to send JS errors right to Slack channel or similar (free)

The main purpose is to catch production errors to prevent bad UX.

**Comment by OAGr** [comment]
Makes sense, Google Stack seems good. How urgent do you think this is?

**Comment by RomanGalochkin** [comment]
It is not urgent of course, but we should do it anyway.

**Comment by RomanGalochkin** [comment]
@OAGr Could you set Google Project up and join me through email "roman.redrat@gmail.com"? All the next steps I will do myself.

**Comment by OAGr** [comment]
Ok, will do so later in the day.

**Comment by RomanGalochkin** [comment]
Sure, no rush

**Comment by RomanGalochkin** [comment]
So are there some updates?
