### ISSUE TITLE
Spend 1-3 hours trying to find security problems with the application

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#486]

**Comment by RomanGalochkin** [comment]
- Hide "auth0Id" field of "User" type

**Comment by RomanGalochkin** [comment]
- Hide "email" field
- Hide "isEmailVerified" field

**Comment by RomanGalochkin** [comment]
- Hide "Preferences" of "Agent"

**Comment by RomanGalochkin** [comment]
- Whats about Agent.Measurements, Agent.Measurables, Agent.Channels?

**Comment by RomanGalochkin** [comment]
- How about list of Channel Memberships? Can we get something thought it?

**Comment by OAGr** [comment]
Hm... I think the main user and agent ones here are the main ones.
