### ISSUE TITLE
[Proposal] Real-Time Interactive Mode

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#500]
It is a proposal for the future stories and application enhancement. When something is being changed the system should update this data somehow on the client side. For instance when Bot adds new measurements user could see changes online without page reloading.

Possible Use-cases:
- One adds measurement (comment, competitive, aggregation) -> update measurement list
- One adds new channel -> update channel index
- One adds measurable -> update measurable index
- One adds/invites member -> update "members" counter
- Activity appears -> update activity index, or even here to show Notification Card? Like when you wait something.

Technology Stack Variants:
- WebWorker
- WebSockets
- Or pulling for the first steps

**Comment by OAGr** [comment]
I think this would be nice, but would definitely be a lot of work for the entire thing. Will consider.
