### ISSUE TITLE
Simple monitoring

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#543]
Make simple monitoring for main urls: 
- foretold.io
- api.foretold.io
- prediction-backend-staging.heroku.com 
- prediction-backend-staging.heroku.com/graphql
- prediction-backend.heroku.com
- prediction-backend.heroku.com/graphql

No matter which one monitoring will be used, even upmt.io.

**Comment by OAGr** [comment]
This sounds good to me.
Did you misspell upmt.io? I can't find it.

**Comment by RomanGalochkin** [comment]
sorry, uptm.io it our service, will do it for me at least

**Comment by OAGr** [comment]
do you have any public services you like/recommend?

**Comment by RomanGalochkin** [comment]
mmm, will review later need something reliable and with function of sharing projects

**Comment by RomanGalochkin** [comment]
so in five days Uptm.io will add something special for these purpose and I will add triggers to notify us through Slack

**Comment by OAGr** [comment]
ok, that sounds good to me. Later we could move to something public.

**Comment by RomanGalochkin** [comment]
Have done for me personally, will change later to add Slack notifications.

**Comment by OAGr** [comment]
Sounds good

**Comment by OAGr** [comment]
I believe this is done? Feel free to re-open if not.

**Comment by RomanGalochkin** [comment]
Yes, I think we could close the issue.
