### ISSUE TITLE
AgentMeasurable GraphQL Type

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#556]
This has two parts:

## Part 1
Add a new GraphQL Type for AgentMeasurable, which is basically the relation between an agent and a question.

```typescript
type AgentMeasurable {
  agent: Agent!
  measurable: Measurable!
  primaryPointScore: float!
  predictionCountTotal
}
```

The primaryPointScore should just return 0.1 or similar for now.
Another option; instead of having the ``predictionCountTotal``, AgentMeasurable could have a field for ``measurements``, which would return a list of edges of the measurements, with a ``total`` attribute, similar to how it's done in other cases. 

### Part 2
Add an ``agentMeasurables`` query.

This should accept the arguments:
```graphql
after
before
first
last
channelId
```

It should return the relevant agentMeasurables.

**Comment by RomanGalochkin** [comment]
@OAGr Do we really need "Part 2" since we have "measurables" query with the parameters of edges and plus "creatorId", "channelId"? Are purpose different?

**Comment by RomanGalochkin** [comment]
Sorry didn't get it from the first time, here it is a representation of new model.

**Comment by OAGr** [comment]
I think it makes sense for this to be different. If we just used the ``measurables`` query, we would need to either run the query for every single combination or creator/channelId, or collect all of them and summarize on demand. 

> Sorry didn't get it from the first time, here it is a representation of new model.
Where is the representation?

**Comment by RomanGalochkin** [comment]
Do we need here new table?

**Comment by OAGr** [comment]
In the database? I imagine we could have a table, but am not sure if it is necessary. I guess it is kind of safe. In the future, we may want to add info about specific users getting access to specific measurables, or following specific measurables, or similar, so a table may be used later.
