### ISSUE TITLE
agentChannel GraphQL Type

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#559]
primaryPointScore should be set to 0 for now. 

This has two parts:

## Part 1
Add a new GraphQL Type for AgentMeasurable, which is basically the relation between an agent and a question.

```typeScript
type agentChannel {
  agent: Agent
  channel: Channel
  primaryPointScore: float!
  numberOfPredictions: int
  numberOfQuestionsPredicted: int
}
```

The primaryPointScore should just return 0.1 or similar for now.
Another option; instead of having the ``numberOfPredictions``, AgentChannel could have a field for ``measurements``, which would return a list of edges of the measurements, with a ``total`` attribute, similar to how it's done in other cases. 

### Part 2
Add an ``agentChannels`` query.

This should accept the arguments:
```graphql
after
before
first
last
channelId
```

It should return the relevant agentChannels.

**Comment by RomanGalochkin** [comment]
@OAGr what is numberOfQuestionsPredicted? so, does it mean that it is a number of "closed" measurables where an agent has done measurements?

**Comment by OAGr** [comment]
yes, good point

**Comment by OAGr** [comment]
maybe numberOfQuestionsPredictedAndScored would be better.

**Comment by RomanGalochkin** [comment]
Here I am going to count measurements with "competitorType" as "Objective", "Competitive", "Aggregation" (since bots can add measurements too).

Feel that should do the same for "agentMeasurables".

**Comment by OAGr** [comment]
Actually, can you just include "Objective" and "Competitive"?

**Comment by RomanGalochkin** [comment]
Sure, will fix

**Comment by RomanGalochkin** [comment]
Fixed.
