### ISSUE TITLE
New Feed Item (user leaves community)

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#563]
Add new feed item when user leaves community.
![Screenshot_20190820_163904](https://user-images.githubusercontent.com/16107421/63352053-0981e180-c369-11e9-9002-045dd28c0667.png)

**Comment by OAGr** [comment]
If we have this, I'm not sure we want to make it prominent. It's kind of depressing.
https://slate.com/human-interest/2018/01/ghosting-the-irish-goodbye-the-french-leave-stop-saying-goodbye-at-parties.html

**Comment by RomanGalochkin** [comment]
Interesting, ok

**Comment by OAGr** [comment]
Thanks for suggesting this though!
