### ISSUE TITLE
All bots shown under every user.

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#565]
Example:
https://www.foretold.io/agents/257c5e1d-ded9-4b73-b426-6e245bbd2924/bots

This used to be a bug, then was fixed, and is now a bug again :(

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/becdf7b7-2894-46cd-b53f-b86163e171a4)

**Comment by OAGr** [comment]
@RomanGalochkin Why did you move this to master? It's broken in prod for me still

**Comment by RomanGalochkin** [comment]
Sorry, had fixed this issues in the previous PR.

**Comment by OAGr** [comment]
sg, thanks!
