### ISSUE TITLE
Able to create question with an empty name

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#566]

**Comment by OAGr** [comment]
Good catch!
To be clear, the user should be able to add someone with EITHER a name or a Subject/Property, but definitely not neither.

**Comment by RomanGalochkin** [comment]
![Screenshot_20190902_110857.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/77ab4221-421c-4d9b-bed3-351c8c576d34)

I think this is node? Or not

**Comment by OAGr** [comment]
I don't understand the question. Do you mean that it is working successfully, because of the server correctly handling the case? I think that is true.

**Comment by RomanGalochkin** [comment]
Sorry, I meant "done", it is the typo error.

**Comment by OAGr** [comment]
ah, k. It looks in the image like it's working about as expected.
