### ISSUE TITLE
Spec out graphql-limiting stories

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#576]
Before really allowing users to use the API, it would be nice to have a few basic additions to make sure we limit requests from destroying the system.

https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b

These two libraries could be good:
https://github.com/stems/graphql-depth-limit
https://github.com/joonhocho/graphql-input-number

It would also be good to have some kind of rate limiting, like:
https://www.npmjs.com/package/graphql-rate-limit
https://www.npmjs.com/package/graphql-rate-limit-directive

We may also want a way to be able to keep track of how much activity different APIs had, and/or allowing some special ones to bypass the main limits (especially our aggregation bot.)

Please describe a set of additions that you feel would be a good "first-pass" at securing our API to semi-friendly APIs. 

Aim for 1-5 days of work for a first pass.

**Comment by RomanGalochkin** [comment]
Like this point, will review later.
