### ISSUE TITLE
Measurable-scores should have more columns

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#581]
- "Prediction" (the competitive distribution)
- "Recent Aggregate" (the recent aggregate)
- "Final Answer" (the last objective answer)

Display these in the ways they are displayed in the regular measurable lists. This is obviously a bit tricky, because the values could vary in type (distribution, specific value, etc)

**Comment by RomanGalochkin** [comment]
![Screenshot_20190828_093231.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/efccfaa0-9844-4430-95ec-72414f5766ea)

@OAGr How I understood I need to add new three columns on that page?

**Comment by RomanGalochkin** [comment]
@OAGr Similar to this?
![Screenshot_20190828_120507.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/bf8a9c79-b5b9-43d8-a979-52f9781b7561)

**Comment by RomanGalochkin** [comment]
Or even more similar to this
![Screenshot_20190828_120944.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/28439856-5471-479c-9b12-8410d89b8d68)

**Comment by OAGr** [comment]
Let's do the second one now

**Comment by OAGr** [comment]
Actually, what exactly was the difference between those two? The first seems zoomed out. The distributions were full for that one.
