### ISSUE TITLE
Measurement scores should have three new columns

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#590]
- "Prediction" (the competitive distribution)
- "Recent Aggregate" (the recent aggregate)
- "Final Answer" (the last objective answer)

Display these in the ways they are displayed in the regular measurement lists. 

This is really what I meant in this story:
https://github.com/foretold-app/foretold/issues/581

Note, I would like the distributions to take the full width of the column; similar to the first image you showed "Similar to this?"

**Comment by RomanGalochkin** [comment]
Did not notice this issue and have done these changes in the PR: https://github.com/foretold-app/foretold/pull/588

So, even after the previous PR here we want to "flexable" distributions, going to do this part in current issue.
