### ISSUE TITLE
Redirect a user after new community was created to this community

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#595]
![Screenshot_20190829_113419](https://user-images.githubusercontent.com/16107421/63924433-f1891c80-ca50-11e9-8d7a-29bc747812d4.png)

**Comment by OAGr** [comment]
I like this one, makes sense

**Comment by OAGr** [comment]
There are probably a bunch of things like this

**Comment by RomanGalochkin** [comment]
Yes
