### ISSUE TITLE
[Optimizations] Separate "total" requests of another

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#608]
For instance we have this query:
```    
query getMeasurablesStateStats ($channelId: String) {
        openState: measurables(states: [OPEN], channelId: $channelId) {
          total
        }
        closedState: measurables(states: [JUDGED, CLOSED_AS_UNRESOLVED], channelId: $channelId) {
          total
        }
        pendingState: measurables(states: [JUDGEMENT_PENDING], channelId: $channelId) {
          total
        }
    }
```

Here we just want to get "total" field, but the server **anyway** will make a query for all measurables thee times. I know it because I had been writing this part of the app. 

I propose to make the next. Just separate the total query from generic query in getAll/getConnection methods of ModelAbstraction layer.

**Comment by RomanGalochkin** [comment]
Here I need to think it over and over again, later will add a plan may be, but now the code is getting too complicated.

**Comment by OAGr** [comment]
Makes sense. If the code is getting complicated, maybe it's worth it to do some heavy refactors or similar some time?

**Comment by RomanGalochkin** [comment]
I do not feel like here we need a refactoring, may be to find a pattern. So, will text here if some thoughts come.
