### ISSUE TITLE
Package @foretold/cdf@1.0.8 for use with observableHQ

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#612]
It would be quite nice to use @foretold/cdf and later other libraries in [observable](https://observablehq.com/) for debugging and statistical analysis. 

Right now this doesn't exactly work.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/d96fc268-21cd-4e88-bc44-dd80596fe751)

To get it to work, we may need to build the library before publishing. Or similar. Observable has a few pages to help explain/debug. 
https://observablehq.com/@observablehq/introduction-to-require

If it did work, I should be able to call functions from the ``cdf`` library, like, ``Samples``.

**Comment by OAGr** [comment]
It would be neat if it worked in iodine as well, which I imagine won't be much more difficult. Can be a separate story if needed. 

https://hacks.mozilla.org/2019/03/iodide-an-experimental-tool-for-scientific-communicatiodide-for-scientific-communication-exploration-on-the-web/

**Comment by RomanGalochkin** [comment]
I feel that we need to publish this pack before using "observableHQ"?

**Comment by OAGr** [comment]
That would make sense, feel free to publish. If you need me to do so let me know.

**Comment by RomanGalochkin** [comment]
Yes, please try to publish cdf, first step is to login through "npm adduser" and then "npm publish --access public". Use you login data from https://www.npmjs.com/

**Comment by RomanGalochkin** [comment]
![Screenshot_20190904_150710](https://user-images.githubusercontent.com/16107421/64253305-ae81ea00-cf25-11e9-8805-a35e67916bcc.png)
iodide is ok too

**Comment by RomanGalochkin** [comment]
![Screenshot_20190904_152012](https://user-images.githubusercontent.com/16107421/64254163-7ed3e180-cf27-11e9-95d2-e6b256d9466a.png)
and observablehq too
so that means we need to publish libs anyway

**Comment by OAGr** [comment]
interesting, looks good.
