### ISSUE TITLE
Simple calculated scoring

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#617]
I've started this, but did a quick job on it, especially with the ``measurements.js`` file. Please clean that up for what you feel is appropriate in the server package, then submit it again.

Also, please make sure the tests pass. For some reason it's failing with travis-ci now.
https://travis-ci.org/foretold-app/foretold/jobs/579513065

**Comment by RomanGalochkin** [comment]
I have fixed code style and tests, please review.
