### ISSUE TITLE
getPreviousAggregate should get the previous aggregate **before** the selected measurement

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#619]
Right now the ``getPreviousAggregate`` gets the last aggregate of the measurable. This is incorrect. It should instead fetch the aggregate immediately before the measurement being scored (perhaps by timestamp)

**Comment by OAGr** [comment]
When was this done? Was this part of #626 ?

**Comment by RomanGalochkin** [comment]
Going to make PR in 5 minutes

**Comment by OAGr** [comment]
Cool, thanks
