### ISSUE TITLE
Foretold users on previous version get error.

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#620]
Users who logged in from a week or two get the error of something going wrong.
""Oops! Something went wrong. Try reloading this page.""

If they delete their localstorage, things work fine (they get logged out, and later get logged back in).

It seems like it's still not fixed; so users with corrupted localstorage settings don't get these erased correctly when there's a problem.

**Comment by RomanGalochkin** [comment]
Hm, could not reproduce this bug, will leave at some time.

**Comment by OAGr** [comment]
Ok, I'll mess with it a bit.

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/65376715-393f4480-dc9b-11e9-818d-9dba700ee7f9.png)

I had it fail on my machine.

On the server, it says that the JWT is invalid.

On the client, it just says that there's an Internal Server Error.
![image](https://user-images.githubusercontent.com/377065/65376722-583dd680-dc9b-11e9-8b95-754cbeb84bb9.png)

Maybe you could reproduce with a bad token? Mine are definitely bad.
![image](https://user-images.githubusercontent.com/377065/65376731-7277b480-dc9b-11e9-88d4-ec48301e1ae5.png)

```
server_jwt 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjE0NDUzODUsImV4cCI6MTU2NDEyMzc4NSwiaXNzIjoiRm9yZXRvbGQiLCJzdWIiOiIwNTQzZDlkNC1kYjM5LTQ3ZWEtYWNjNy00YzFiYTBlOWVkMGIifQ.mZF6JjsIoa1-lwr5iq2hResy5BhKC0B10UKnTCuFpww

expires_at
1566721829018

id_token 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnaXZlbl9uYW1lIjoiT3p6aWUiLCJmYW1pbHlfbmFtZSI6Ikdvb2VuIiwibmlja25hbWUiOiJvenppZWFnb29lbiIsIm5hbWUiOiJPenppZSBHb29lbiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vLTFzajNFcWtvako0L0FBQUFBQUFBQUFJL0FBQUFBQUFBQUFBL0FDSGkzcmZXQ1ZxbnVKeHhNNDFaaXJkNEhaeDBCYlJwYlEvcGhvdG8uanBnIiwiZ2VuZGVyIjoibWFsZSIsImxvY2FsZSI6ImVuIiwidXBkYXRlZF9hdCI6IjIwMTktMDctMjVUMDg6MzA6MzIuNzU4WiIsImVtYWlsIjoib3p6aWVhZ29vZW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vZm9yZXRvbGQuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA5ODczMjA2MzQ0OTgwNjE0ODc5IiwiYXVkIjoib0loNTNvaEJuQTR4cWhhTzh2WlhhN1BpVzZUQ1hqTVYiLCJpYXQiOjE1NjQwNDM0MzIsImV4cCI6MTU2NzY0MzQzMiwiYXRfaGFzaCI6ImZKRVktOERJbldSQzVGanZlTVlXNGciLCJub25jZSI6ImtrZHRBQ1lkZV9kNG1-aUVqcFJ5bWFTd2RjZ3hPMDVaIn0.MJ-gB3980MCpS_Voav330iksVYmKMxXvWTPCEIIXqW4

access_token
9DJ52E8SuNf9ppp50mtpWCohyzyC-7-_
```
