### ISSUE TITLE
Write small js library for handling numeric measurement types

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#624]
The scoring is already getting messy. 

The ``client`` has a nice ``MeasurementValue`` file, which allows for all types of measurement values to get treated similarly.

The server doesn't really have something equivalent yet.

This becomes particularly important for scoring, where there are several technicalities for different situations.

We have three options for dealing with this, really:
1) Go Reason-ml first. Make a new lib with the shared functionality. Use [gentype](https://github.com/cristianoc/genType) to make a small js library from that reasonML library.
2) Go JS first. Make a new lib with the shared functionality. Make a reasonml wrapper.
3) Have both a ReasonML and a JS library.

I'd be curious to get your thoughts on which you'd prefer. 

The important piece for this story is that we have something better set up in the server, which will need it.

**Comment by OAGr** [comment]
Please think about this and write a recommended approach first; then we can agree on it before you start this.

**Comment by RomanGalochkin** [comment]
What should this lib do? Do not understand properly.

**Comment by OAGr** [comment]
Hm... it may be hard to fully explain. The main thing is just to hydrate records from json or similar to treat them as js or reasonML classes. Then we'll want that to do validation and scoring and stuff.

We don't really have models or hydration records in the backend for the different value types, we just treat them a bit on-the-fly.

![image](https://user-images.githubusercontent.com/377065/64168773-2a0b6a80-ce44-11e9-8971-4f3cb040f843.png)

This will get messy the more we use these on the backend. We may want a library we could do commands like:

```js
let prediction = new ValueType({dataType: args.input.value.dataType, data: args.input.value.data});
let prediction = prediction.isValid();
let predictionType = prediction.getTypeAsString(); //"percentage", "cdf"....
```
Then later we could do
```js
let prediction = new ValueType({dataType: args.input.value.dataType, data: args.input.value.data});
let aggregate = new ValueType({...});
let finalValue = new ValueType({...});
let score = new PredictionAggregateScore({prediction, aggregate, finalValue});
```

Does that make sense and/or seem useful? If it's not apparent than just work on the next thing.

**Comment by RomanGalochkin** [comment]
Ok, got you, will add re-hydration classes (models) for this and then show to you to approve.

**Comment by OAGr** [comment]
Sounds good. Just to be clear, of the "three options" I listed above, which do you intend to go with?

**Comment by RomanGalochkin** [comment]
I think the most convenient way is to write this lib on both language (RML, JS). To write wrapper for JS with RML does not have a sense for me now and is not obvious. But how do you think, what would do you prefer?

**Comment by OAGr** [comment]
That's fine. If they get too complicated we could combine later
