### ISSUE TITLE
Figure out Agent-Measurable Scoring Backend

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#626]
I'm figuring out the agent-measurable scoring. It's kind of tricky.

To do scoring, we'll need to load:
- all of the competitive measurements a specific user has made, with timestamps
- all of the aggregates made after that, and the aggregate made immediately before that, with timestamps
- the most recent result, with a timestamp
- the timestamp of when the measurable was created.

These will all go into a function that will calculate the user score. I'm going to work on making the score (it's not too complicated), but the rest seems tricky and I'd like to have it started.

Questions:
- Should we compute this on-demand, or save it to a db in a ``AgentMeasurable`` table or similar? If we save it, how should we manage it being updated? (It just has to update when new objective results come in, which is kind of nice)
- Can we for-now have a proxy question, which just loads all of this, and returns a score of [number of user competitive measurements * 10] + [number of aggregates after, plus 1 before, times 1].?

**Comment by RomanGalochkin** [comment]
Is there a way to make calculations right on the DB side? I think yes.

**Comment by RomanGalochkin** [comment]
I feel that I could write a SQL for this, it would be better if to count that it is a dynamic

**Comment by RomanGalochkin** [comment]
My plan:
1. To add SQL for this.
2. To pass it into special JS function or to return using graphql query.

**Comment by OAGr** [comment]
Can you be more descriptive? When you say "add SQL", do you mean add complexity to the VIEW, or make a new table?

**Comment by RomanGalochkin** [comment]
I mean raw SQL for a query to get data. It may will be view, I did not decided yet, working on it.

**Comment by RomanGalochkin** [comment]
"Can we for-now have a proxy question", talking about this, where do we want to place a graphql query for this?

**Comment by OAGr** [comment]
Sounds good. I think the actual function would have to be in javascript,
loading the ``cdf`` library.

Separately, we'll likely want all of this data available to users so that
we can show it in graphs to explain their scores. We may want to load it a
bit differently then though.

**Comment by OAGr** [comment]
The query should just be in the place we currently get the agent-measurable score. The answer will go into this table, in the ``total score`` column.

![image](https://user-images.githubusercontent.com/377065/64109012-5062d480-cd76-11e9-8068-c3a3d349aec5.png)

That said, we may also want to pre-compute it and save it in the database.

**Comment by RomanGalochkin** [comment]
Ok

**Comment by RomanGalochkin** [comment]
I have added a simple SQL query here. Do we need values of these measurements to get score points?

**Comment by OAGr** [comment]
We need all the measurements described in the top of this to get Question Scores.

```

    all of the competitive measurements a specific user has made, with timestamps
    all of the aggregates made after that, and the aggregate made immediately before that, with timestamps
    the most recent result, with a timestamp
    the timestamp of when the measurable was created.

```

They're pretty messy.

**Comment by RomanGalochkin** [comment]
We have.

**Comment by RomanGalochkin** [comment]
I mean "dataValue" field.

**Comment by OAGr** [comment]
Ah, yea, the important bits are the ``dataValue``s and the timestamps.

**Comment by RomanGalochkin** [comment]
Well then it's ok.
