### ISSUE TITLE
Upgrade high-severity and critical-severity dependencies

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#628]
Message me for google doc

**Comment by RomanGalochkin** [comment]
Link to doc
https://docs.google.com/document/d/199sJitc-tWkymZRDzb_acIyZZ1G8y2lmVizlRQQA7Zk/edit

**Comment by RomanGalochkin** [comment]
I think these libraries are nested into other third party dependencies so we cannot upgrade them or replace them.
