### ISSUE TITLE
Round scores to two decimals

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#631]
Currently displaying too long strings, see image: 

<img width="908" alt="Scoring decimals" src="https://user-images.githubusercontent.com/21347592/64167961-cd5f7e00-ce4a-11e9-9da1-046d425caf3c.png">

**Comment by RomanGalochkin** [comment]
Was done 5 minutes ago.

**Comment by OAGr** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/377065/64172863-cd14b200-ce4d-11e9-8c9f-1ca55596bc8a.png)
