### ISSUE TITLE
Spec out plan to cache measurement-scores 

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#642]
The measurement scores seem to take a while to load, and we'll need them a lot for the other scores.
I'm thinking we add columns for the different score types, and calculate all of them whenever:
1) The first result is added
2) Any competitive, aggregate, or objective measurement is added.

Some ways we could do this (in order of challenge):
1) Do it in the mutation itself, making the mutation take a while.
2) Flag the questions that need scoring. Have a bot trigger the server at 5min intervals or so. 
2) Add a background job setup, and create a background job for it (this seems like the best way, but it could take some set up).

**Comment by RomanGalochkin** [comment]
Just going to place some pictures with descriptions here and later probably use in conversation as link to:
![Screenshot_20190905_094629](https://user-images.githubusercontent.com/16107421/64318147-0a01b580-cfc2-11e9-82d8-6c9a3c086c80.png)
1. getMeasurables, server = 0.49s, network = 2.08s

**Comment by RomanGalochkin** [comment]
Looking at picture 7 we see that the biggest part of time (73%) is gone to downloading. And only another 27% need for a server work. 
I think that to make optimizations right now is too early. Anyway it won't give to us much result.

**Comment by RomanGalochkin** [comment]
Between if we want to optimize something we need to optimize server responses first of all and only then calculations. 

Premature optimization is a killer of applications number one. Dead-pool.

**Comment by OAGr** [comment]
Hm... good point. 

17s for the main files is bad, but a separate optimization.

Do you have ideas for some cheap wins?

For example, maybe only sending a fraction of all of the samples of the floatCdfs would help? I'm not sure why the graphql size is so large. 

We could also set up a profiling system.

I agree that premature optimization is pretty bad, but very slow websites is also pretty bad. There's often space between.

**Comment by RomanGalochkin** [comment]
May be for distributions we could make an approximation? For instance xs: [-10, -5, 0, 5, 10] ys [1, 2, 3, 4, 5] ---> [-10, 0, 10] [1, 3, 5] or similar and return this data under another fields?

**Comment by RomanGalochkin** [comment]
Or even try to use some compression algorithms to reduce a size of data?

**Comment by RomanGalochkin** [comment]
And another one solution is to load distributions in another queries. 
Step 1 is load measurements. Step 2 is to load distributions and show it.

**Comment by OAGr** [comment]
Yea, both are quite doable. I think I like the idea of compressing them, for instance, summarizing the graphs in 2000 samples, instead of needing 10k. Do you have an idea of how much of the entire data sent over is in these Cdfs?

**Comment by RomanGalochkin** [comment]
Do not know exactly but I think a lot

**Comment by OAGr** [comment]
I put the x-samples into a doc.

I could imagine some fancier compression schemes, but to make things simple, how about we do the following: 

MeasurementValue -> floatCdf has multiple options.

```graphql
MeasurementValue {
  floatCdf { 
    formats {
     complete { xs, ys}
     abridged {xs, ys}
   }
  }
}
```

The ``abridged`` version would only return ~150 points, instead of 1000x10000.

In the future we may also want functionality like,

```graphql
MeasurementValue {
  floatCdf { 
    formats {
     completeCdf { xs, ys }
     completePdf { xs, ys }
     abridgedCdf { xs, ys }
   }
   summaryStatistics {
     mean
     median
  }
  applyFunction(function: "x * 23"){
    formats{...}
  }
}
```

**Comment by RomanGalochkin** [comment]
Or event decorators?

**Comment by RomanGalochkin** [comment]
@short() floatCdf

**Comment by OAGr** [comment]
Oh, good idea. My impression is that decorators aren't very common yet? Are they supported by reason-apollo? (I don't see anything about them)

**Comment by OAGr** [comment]
It could be worth a quick experiment to see if they can be used with this setup. The node side seems much safer, I assume.

**Comment by RomanGalochkin** [comment]
Yes

**Comment by OAGr** [comment]
I'm pretty sure the ``formats{completeCdf}`` version would work. Can you make a story to try out decorators and see if you could get them working on both the client and the server, for a trivial case?

**Comment by RomanGalochkin** [comment]
sure
