### ISSUE TITLE
[Optimization] Optimize "scoring" graphql client queries

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#646]
We need to optimize these queries
![Screenshot_20190906_095808](https://user-images.githubusercontent.com/16107421/64407372-d63f9200-d08c-11e9-8552-67432667bef0.png)

And I'm sure that there are another queries we may optimize, it would be good for UX.

**Comment by OAGr** [comment]
Hm... This page may be changing. The much more frequently visited pages will be the Measurable Index pages (home pages / channel pages) and the measurable pages. Those are still quite slow, could use speeding up.

**Comment by RomanGalochkin** [comment]
We have removed all I wanted to optimize.
