### ISSUE TITLE
Bots links lead on the wrong page

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#647]
![Screenshot_20190906_105302](https://user-images.githubusercontent.com/16107421/64410803-806ee800-d094-11e9-9980-b7052253fd90.png)

**Comment by OAGr** [comment]
Can you describe this a bit more? I'm not sure I follow.

**Comment by RomanGalochkin** [comment]
Here if we click on the bots name we will go on the wrong page.
