### ISSUE TITLE
Couldn't figure out how to resolve a question

### ISSUE THREAD

**Issue by brachbach** [foretold-app/foretold#653]
(UX feedback)

I spent about 2 min trying to figure out how to resolve a question that was pending resolution (https://www.foretold.io/c/2a6f08ab-6471-48e2-9cfd-7e398b93f8a0?state=pending), and couldn't figure out how to resolve it.

I think the UX for resolving questions should be more clear.

Also, more practically for me now -- how *do* I resolve a question?

**Comment by OAGr** [comment]
Thanks for letting me know!

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/377065/64563446-5133d180-d347-11e9-8560-947d3a9d39a3.png">

If you own the question (if you made it), you can click on "Predict", then select "Resolve". This allows you to resolve it.

**Comment by brachbach** [comment]
Thanks, that worked!

**Comment by OAGr** [comment]
Cool, thanks! We definitely have some UX-cleanup work to get to. Let me know if you have other issues.

**Comment by brachbach** [comment]
FWIW I just had to search for this issue again to relearn how to resolve predictions :p
