### ISSUE TITLE
[Server] Refactoring

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#668]
1. packages/server/src/models-abstract/channel-membership-model.js
To remove these methods since we do not need it (see parent's class methods):
- updateOne
- deleteOne

2. packages/server/src/models/channel.js 
Fix "getMembershipCount" use another ways of doing thise, and do the same for another similar places (resolutionEndpointResponseGetter, getMeasurementCount, getMeasurerCount).

3. To move "watchExpectedResolutionDate" method from measurable model upper.

4. To move "getCreationNotification" and "getUpdateNotifications" from measurable model somewhere else, for instance on hooks layer. But do not leave it here.

5. To move "getCreationNotification" from measurement model. 

6. To move "createMeasurables" from series model somewhere else. Models definitions should have the simplest form.

7. Rename "async" folder to "sync". There are not **asynchronous** flows, there are **synchronous** flows.

8. packages/server/src/data/channel-memberships-data.js
Removes these duplicated places:
- createOne2
- updateOne2
- getOne2
- getAll2

9. packages/server/src/data/channels-data.js
- createOne (remove)
- getAgentsByChannelId (move down on models-abstract layer, see Law of Demeter)
- getCreatorByChannelId (same)

10. packages/server/src/data/measurables-data.js
- createOne (fix)
- updateOne (fix)

11. packages/server/src/data/measurements-data.js
- createOne (fix)
- getLatest (move down)

12. packages/server/src/data/series-data.js
- createOne (fix)

13. packages/server/src/async/measurables/reducer.js
To give more meaningfully name.

**Comment by OAGr** [comment]
Looks good, feel free to do this whenever is convenient.

**Comment by RomanGalochkin** [comment]
For me, want to track step by step:
- [x] 1
- [x] 2
- [x] 3
- [ ] 4  - doing, testing
- [x] 5 - testing, 
- [ ] 6
- [x] 7
- [x] 8
- [ ] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
