### ISSUE TITLE
Implement ChannelAgent PrimaryPointScore

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#674]
This score should be equal to the sum of an agent's question primaryPointScores.

**Comment by RomanGalochkin** [comment]
The time complexity of the algorithm:
O (QueryAgentChannels · {AgentChannels}<sup>T</sup> · {Measurables}<sup>T</sup> · {Measurable, Measurements}<sup>T</sup>) = O(1· n · n (1 + n)) = O(n<sup>2</sup>(1 + n)) ~ O(n<sup>3</sup>)

Just was interesting to know.
