### ISSUE TITLE
Get Guesstimator working in ObservableHQ

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#691]
Whenever I try it with bundle.run it shows up empty. 

I tried setting it up with microbundle and with rollup. You can see them with these branches:
https://github.com/foretold-app/foretold/tree/microbundle
https://github.com/foretold-app/foretold/tree/rollup-guesstimator

Right now it says that it's working by catching the window, but it shows up empty. 

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/2aeceb13-4b3f-4a1a-9c63-b9b065b74175)

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/97e43165-23b2-42b3-9323-9399bd2ac342)

Make sure it's at least working with one of the setups. Second, try to figure out how to get it to work with any of the other techniques other than using bundle.run or .catch(), which are both pretty hacky.

**Comment by RomanGalochkin** [comment]
1. The package has to be bundled via a bundle tool like "parcel", "webpack" or another one.
2. It seems "observablehq.com" like does not load "third-libs" requirements of the JS file.
3. This is why when you publish a package it should contain bundled files.

**Comment by RomanGalochkin** [comment]
![Screenshot_20190920_111047](https://user-images.githubusercontent.com/16107421/65310579-4e32af80-db97-11e9-9473-a09f90698ef6.png)

https://observablehq.com/d/6e08fb4a91c70155

**Comment by RomanGalochkin** [comment]
4. And another main thing is that "ObservableHQ.com" uses "jsdelivr.com" as CDN of NPM pckages even you use "require('@foretold/guesstimator@1.0.8/dist/main.umd.js')". And this is good.
Open console log then the network tab and you will see requests like this:
`https://cdn.jsdelivr.net/npm/@foretold/guesstimator@1.0.8/dist/main.umd.js`

**Comment by OAGr** [comment]
Yep, I was expecting that this task included getting it set up with a bundler. I was thinking Rollup or similar, something to package it in a few different formats for easy use, so it would do well in their debugger.

**Comment by OAGr** [comment]
https://observablehq.com/@tmcw/module-require-debugger

**Comment by RomanGalochkin** [comment]
Even we use "microbundle" or similar do they support ES6/7/8 and so on? Do not think so.

**Comment by OAGr** [comment]
It wasn't obvious to me. I assumed so, but maybe not. But if not, shouldn't one of the bundlers, or just babel, be able to convert it down?

**Comment by OAGr** [comment]
Ooh, I guess microbundle doesn't. 
https://github.com/developit/microbundle/issues/304

Maybe we should add babel as well?

**Comment by RomanGalochkin** [comment]
I think the best way is to create bundle file anyway. For what do we need decomposed modules?

**Comment by OAGr** [comment]
Looks like we'd also need babel to use rollup.
https://github.com/rollup/rollup-plugin-babel/issues/312

**Comment by OAGr** [comment]
I just assumed that decomposed modules would be useful for speed and using the code on ObservableHQ and similar platforms. It's quite possible we don't need them. Seems like at least babel is important though? 

If so, maybe you need to add babel or similar, and make sure there's a building system before publishing to npm? I'm not sure exactly what it was like when you got it locally working.

**Comment by OAGr** [comment]
I guess parcel does do the es6 / babel conversion, which is nice.

**Comment by RomanGalochkin** [comment]
Yea, this is why it's working.

**Comment by RomanGalochkin** [comment]
Will try babel and decomposed modules on the next task. Interesting does it work or does not.

**Comment by OAGr** [comment]
Thanks, sounds good. This is really useful.

**Comment by OAGr** [comment]
w00t, observablehq works fine now. Just pushed a newer version.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/377065/65314232-d2803500-db8d-11e9-861e-6bec39f555d9.png">

**Comment by OAGr** [comment]
I think decomposed modules would still be interesting though. They should be cleaner / easier to debug / smaller I believe

**Comment by RomanGalochkin** [comment]
Sure, going to try to make it work.
