### ISSUE TITLE
Get prediction-analysis lib working in ObservableHQ

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#692]

**Comment by RomanGalochkin** [comment]
I was thinking about it and have understood a thing. There are no another ways to use not bundled files, only bundles. 

`import {vl} from "@vega/vega-lite-api"`
This import works only **on the top level**. I mean that it loads ordinary bundled file. That bundled file is UMD. 

So I do not imagine how to use decomposed modules with "require(./...)", "require(lodash)" or "import {} from "". It should not work anyway.

**Comment by RomanGalochkin** [comment]
And I have noticed that "require("@foretold/guesstimator@1.0.9");" works the same as "require('@foretold/guesstimator@1.0.9/dist/index.js')". I think it is because package.json links to this file inside itself.

**Comment by OAGr** [comment]
Yep, the package.json links specifically to that file.

**Comment by OAGr** [comment]
I'm not exactly sure what you mean by the first comment. I imagine in this case we could just make sure that the package.json links to the same file, and be ok?

**Comment by RomanGalochkin** [comment]
I meant that we always have to use only bundles. I was trying to understand will it work if we create separated files instead of only one file in "dist" directory.

**Comment by RomanGalochkin** [comment]
![Screenshot_20190920_155828](https://user-images.githubusercontent.com/16107421/65328662-7d5d1700-dbbf-11e9-8d41-b1d8ae500a29.png)

**Comment by OAGr** [comment]
That looks pretty good
