### ISSUE TITLE
SSL Issue 

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#711]
SSL doesn't seem to be correctly working in new browsers that haven't already used Foretold. I imagine this is a Heroku issue. 

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/f58dddfb-cae4-41c7-8867-13f4db98af97)

**Comment by OAGr** [comment]
This was pointed out by someone else, and I replicated it in Safari.

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/65822688-47173b80-e240-11e9-95c8-bacfe1859e26.png)
![image](https://user-images.githubusercontent.com/377065/65822691-4b435900-e240-11e9-9991-581adfeb57a6.png)

**Comment by OAGr** [comment]
I think I had this figured out. The issue was an old a record for foretold.io without the www

**Comment by RomanGalochkin** [comment]
Ok.
