### ISSUE TITLE
Non-aggregation bot scores still aren't showing 

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#713]
Here you could see that "second bot" made a prediction.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/b1b0a716-1f75-458b-aeb8-0b6b9293dd28)

But the score doesn't show.
![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/ad3240b9-b91d-4b26-a358-65c1ca9517b3)

It also doesn't show on the channel scoring tab.
![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/3146cbbc-b1e7-490b-a5de-9a026ff1f440)

**Comment by RomanGalochkin** [comment]
I could not reproduce this bug, may be it was a cache of Apollo requests?

**Comment by RomanGalochkin** [comment]
![Screenshot_20190930_085258](https://user-images.githubusercontent.com/16107421/65852726-b6d01800-e35f-11e9-871d-1c711c368d15.png)
![Screenshot_20190930_085319](https://user-images.githubusercontent.com/16107421/65852737-c0f21680-e35f-11e9-95d6-17be844cfa17.png)
![Screenshot_20190930_085343](https://user-images.githubusercontent.com/16107421/65852757-cfd8c900-e35f-11e9-82e2-60354bf40fec.png)

**Comment by RomanGalochkin** [comment]
![Screenshot_20190930_085440](https://user-images.githubusercontent.com/16107421/65852796-f3037880-e35f-11e9-90e5-d9f9be384d44.png)

**Comment by OAGr** [comment]
Weird. I messed with it some more and still had it mess up. 

Here's a community where it's a problem:
https://www.foretold.io/c/b4ddcc41-59b4-44df-b223-dea32fa8c9d8?state=closed

**Comment by RomanGalochkin** [comment]
It turned out that we forget to run migrations. Sorry, had to remember about migrations in that PR.

**Comment by RomanGalochkin** [comment]
I have run migration, now it seems all is ok.
