### ISSUE TITLE
Rename "Name" to "Question title" or "Question (short version)"

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#719]
<img width="665" alt="Question creation" src="https://user-images.githubusercontent.com/21347592/65946347-3f20ec80-e436-11e9-86a8-6233a8e1ae09.png">

When running a prediction session during the recent rationality workshop, at least 5/20 people interpreted and wrote "Name" as their own name, rather than the actual question.

**Comment by OAGr** [comment]
Heh, that's good to know. "Question Title" seems good to me.
