### ISSUE TITLE
Make the default resolution for "numbers question" be "Exact value" rather than "Distribution" [2.8, 2]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#729]
When resolving a question, the default in the dropdown menu is "Distribution", and one has to open up the exact meny to pick "Exact value". 

I expect this will be confusing for new users. 

<img width="249" alt="exact value" src="https://user-images.githubusercontent.com/21347592/66205240-3128d100-e6ad-11e9-94c3-7c2fc18eeac6.png">

**Comment by OAGr** [comment]
Good point. I imagine though that it would be even better to just not ask users to fill that out, and instead just figure it out for them automatically? If they enter "7" it will be an exact value, if "5 to 10", it would be a distribution.

The reason why it was done like this was to temporarily save engineering time.

**Comment by OAGr** [comment]
Also, I'm changed this from a bug, because something isn't exactly "broken"; it's more that the design was suboptimal and could be improved.

**Comment by lagerros** [comment]
Yup, I thought about that as well, and it would be better, but suspected it would be a bit of a technical schlep.

Also, for the second point I didn't use the enhancement category because it also inolved "feature requests" which seemed like a bigger thing than this. Might call it "polish" or something

**Comment by OAGr** [comment]
Makes sense.

FYI, some programmers get emotional about bugs, as it indicates mistakes they have made, so the distinction is often significant to them.

**Comment by OAGr** [comment]
I think this won't be needed once we have this:
https://github.com/foretold-app/foretold/issues/731
