### ISSUE TITLE
If my email is not verified, the system should check if my email was verified on every page change or similar. 

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#733]
We don't want to force them to log out and log back in, which is a pain.

**Comment by OAGr** [comment]
Another option for this would be to have a button that they can click to refresh. This button would show in the alert. The button would say "I have done this", and it would reset it.

**Comment by RomanGalochkin** [comment]
Here all is ok, I just need some time to write a code (branch 733-check-session) . It already works.
