### ISSUE TITLE
[Refactoring] Client

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#746]
- To remove module "LoggedInPage". 
- To remove "Pages.re". Instead of this to use <ComponentStyle>.
- To rename "graphql.inner" to "graphql.component" (to make calls similar to get better code searching).
- To change all mutations to use <ComponentStyle> (2-4 places in the code).
- To move the"Antd" directory from the Utils to the Lib folder.
- To move all stuff into the Utils lib ("AppApolloClient.re", "E.re", "HttpResponse.re", "Providers.re", "Redirect.re").
- To repair Apollo Instance: to make sure that the "instance" function returns independent instance of "ApolloClient" and its requirements like "links".

**Comment by OAGr** [comment]
Feel free to prioritize at your discression
