### ISSUE TITLE
Duplicated prediction from bot

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#756]

**Comment by OAGr** [comment]
I noticed this bug when I changed the frequency of the bot running to once every ~5 minutes I think.

**Comment by RomanGalochkin** [comment]
This note for me. We should make sure that "relevantAt" and "createdAt" is the same date. Look at the tail of Datetime Stamp, the difference so small so this is hardly ever noticeable. 

![Screenshot_20191017_095811](https://user-images.githubusercontent.com/16107421/66985046-a2607f00-f0c4-11e9-8939-adcca38adfb0.png)

**Comment by RomanGalochkin** [comment]
@OAGr And may be do you remember how did you set "AGGR_SCHEDULE" var?

**Comment by OAGr** [comment]
I think it was something like "*/5 * * * *", but I may have had it a bit different.
