### ISSUE TITLE
To add a title for the app

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#816]
![Screenshot_20191101_110328.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/5f577c57-ed07-4ba5-af75-2c81bf85f101)

**Comment by OAGr** [comment]
Doesn't this have a title? "Foretold.io".

Do you mean page names, like, the same as the channel?

**Comment by RomanGalochkin** [comment]
Yes, for instance.
