### ISSUE TITLE
Diagnose the timeout and "critical" server issues

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#828]
We've been getting tons of warnings from Heroku. Also, the site is very slow at times. 

Please investigate the logs to figure out what is slowing it / causing issues, and suggest fixes.

For this story, you don't have to implement these fixes, just recommend them.

![image](https://user-images.githubusercontent.com/377065/68166647-e378e000-ff5a-11e9-8420-c09a05fb36d7.png)

**Comment by OAGr** [comment]
I'm pretty sure this was due to a one of us doing a lot of queries on scoring.

**Comment by RomanGalochkin** [comment]
I'm definitely sure that it corresponds to #829 issue. So the one way to fix this is to fix the issue #829.
