### ISSUE TITLE
Brainstorm ways to make scoring server calls faster

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#829]
Right now calls to get the ``primaryPointScore`` and similar are very slow; so slow that one user calling them can slow the app for everyone.

This really could use some speeding up somehow.

Some ideas:
1. We have a cache of previous aggregates and previous predictions in Reddis or similar.
2. We cache the actual scores.
3. We do analysis on the computations to figure out what parts care causing the slowdown (probably the first step)

**Comment by RomanGalochkin** [comment]
Let's suppose that we are talking about only one query from the page of "#Amplifying spot-checks - Scores - Member Scores". It is the typical query.

1. I believe that here we do not have to apply cache. This is why. One of the valuable parts of time waiting is getting "numberOfPredictions". For instance, it will cost at least 6-7 seconds. We could rework it somehow (to count prediction in a background mode or similar).
2. The channel "#Amplifying spot-checks" has 65 members, and only 25 of them made predictions. This channel has 68 measurable. 
- So to show that page with the members` scores we need to query "agent channels" with filtering by "numberOfPredictions". 
- Then we need to fetch 68 measurables.
- And then for each iteration (like for a "map" function), we need to fetch again one measurable and all measurements for this measurable.

This simple calculation will show the number of DB queries: {1 Get Agent Channels}x{25 Agent Channels}x{68 Measurables}x{1 Measurable, 1 Measurements} = 1*25*68*2 = 3400.

So we could optimize queries here:
2.1) We could pass measurable deeply to prevent obsolete queries.
2.2) We could query only necessary attributes ("relevantAt", "value") of Measurements.
3. And only then we again could think about cache. So, first of all, we need to fix code and algorithms.

**Comment by OAGr** [comment]
I'm happy to begin with some of those optimizations and see how things get. 

Maybe make stories for the most impactful 2-5 points, then we could prioritize accordingly? I'd prefer to keep the system flexible if possible; I imagine we'll change the scoring system decently in the next few weeks.
