### ISSUE TITLE
Guesstimator package cleanup

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#836]
The guesstimator lib could use more work.

1. There are lots of devDependencies. Remove the ones that aren't needed. Also, I'm not sure if parcel needs to be a dependency instead of a dev dependency. 

2. The important files should be in a ``src`` lib. Right now index.js, types.js, the ``formatter`` lib, and the ``samplers`` libs are all top-level, which isn't good.

3. Testing doesn't seem to work.

4. A small readme of how to use it would be nice.

**Comment by RomanGalochkin** [comment]
We use "parcel" as "dependency" because on the Heroku side production mode is set. This is because we need to make distribution bundle.
