### ISSUE TITLE
Make sure that the /components/prediction-analysis tests work

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#840]
Right now they fail for me. Seems like a parcel/build issue.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/0a17d3d3-6692-4c0a-bc54-06f78cdc6995)

**Comment by RomanGalochkin** [comment]
![Screenshot_20191107_114004](https://user-images.githubusercontent.com/16107421/68373159-58af0580-0153-11ea-993d-ebc8f0d4cbfa.png)
It seems like this is working ok on my local machine.

**Comment by RomanGalochkin** [comment]
I am going to turn on these tests in the Travis flow, will push into the previous #841 PR.
