### ISSUE TITLE
Error on the production

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#845]
`Error! [GraphQLError: f.combineWithUniformOfCdf is not a function] { message: 'f.combineWithUniformOfCdf is not a function', locations: [ { line: 74, column: 11 } ], path: [ 'measurements', 'edges', 4, 'node', 'measurementScoreSet', 'nonMarketLogScore' ], extensions: { code: 'INTERNAL_SERVER_ERROR' } }`

**Comment by OAGr** [comment]
It should be fixed now
