### ISSUE TITLE
To give a small description for fields and objects of Graphl's schema

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#846]

**Comment by OAGr** [comment]
This was done recently, right, for a few definitions?

**Comment by RomanGalochkin** [comment]
Yes, if we mean only four fields. I do not imagine how to add description for another fields. They are obvious. I do not remember exactly but the issue was corresponded to some date fields.

**Comment by OAGr** [comment]
Ok, that works, I'll move to closed
