### ISSUE TITLE
Have question submitted via the API without resolution date default to resolve n days in future [2.2, 1.8]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#854]
Currently n = 0, which is quite annoying (e.g. it caused bug #853 ). It's also a strange an probably non-standard use case whereby things resolve that quickly.

**Comment by OAGr** [comment]
It would be easy to set the default later. Any recommended time? 2 days maybe?

**Comment by lagerros** [comment]
1 month. Would have been more helpful in my experience.
