### ISSUE TITLE
Make the communiy description input window larger by default

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#855]
When editing a community description, the input window is quite small, which is very annoying. It's resizable, but we should still make this easier for users by default.

**Comment by OAGr** [comment]
This good? This is 30em, which is quite large.

![image](https://user-images.githubusercontent.com/377065/68807334-8d452480-065f-11ea-9012-c5cc4a0d6f74.png)

**Comment by lagerros** [comment]
That's great, thanks!
