### ISSUE TITLE
Display large numbers using K/M notation on x-axis [3.8, 4]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#860]
E.g. 10000000 should be rendered as 10M. 

Currently all the zeros are rendered causing overlap and unreadable numbers.  

<img width="363" alt="messed up x axes" src="https://user-images.githubusercontent.com/21347592/69064494-95fe7780-0a1e-11ea-99ae-9801c9a3081b.png">

**Comment by lagerros** [comment]
@OAGr updating on the importance on this as some question from Against the grain will have larger ranges (e.g. "human population in 10000BC" -- my initial outside view was 100k to 100m)

**Comment by NunoSempere** [comment]
I made a pull request on this; waiting for approval

**Comment by OAGr** [comment]
It's merged, but deployment is kind of stuck. It should be fixed soon though.
