### ISSUE TITLE
Make clickable cell in notebooks larger when it has 0 predictions

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#861]
Currently if a measurable has 0 predictions, you can only click on it to open the sidebar by clicking on a thin slice at the top. It would be better if the entire cell was clickable, as for the measurables that already have predictions on them.

<img width="215" alt="too thin" src="https://user-images.githubusercontent.com/21347592/69235385-94a18c00-0b91-11ea-8c9a-9bbbae361b8d.png">

**Comment by OAGr** [comment]
This should be fixed now, thanks!
