### ISSUE TITLE
The measurements query should sort by relevant_at

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#862]

**Comment by OAGr** [comment]
Right now it seems to sort by created_at or similar. Most of the time relevant_at is more important.

**Comment by RomanGalochkin** [comment]
It seems like this works as we expected already. I am getting measurements always sorted by "relevat_at".

![Screenshot_20191128_082649](https://user-images.githubusercontent.com/16107421/69779358-d39a9780-11b8-11ea-9853-8141ae4c5901.png)

![Screenshot_20191128_082719](https://user-images.githubusercontent.com/16107421/69779382-e614d100-11b8-11ea-8bb5-3fe6cebc0b61.png)

**Comment by OAGr** [comment]
Strange. Can you check this question:
https://www.foretold.io/c/f19015f5-55d8-4fd6-8621-df79ac072e15/m/5be0fba1-5701-4a83-816b-0ee4ab71073a

![image](https://user-images.githubusercontent.com/377065/69804647-f3d94f00-11d6-11ea-8701-23ae75d61df7.png)

I'm confused why there are two competitive measurements, followed by two aggregates

**Comment by RomanGalochkin** [comment]
Oh, yes, see, will investigate.
