### ISSUE TITLE
Notebooks show duplicated forecasts even for logged out users/when I haven't made forecasts

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#863]
C.f. below. I have made no forecasts on the notebook in question!

*Logged out*
![image](https://user-images.githubusercontent.com/21347592/69327913-9e3cf980-0c4e-11ea-8e70-7512d11cfb95.png)

*Logged in*
![image](https://user-images.githubusercontent.com/21347592/69328109-f4aa3800-0c4e-11ea-8502-d64f429257e0.png)

**Comment by OAGr** [comment]
Hm... I can't seem to reproduce yet.

**Comment by OAGr** [comment]
Oh, got it. The problem is that when a question is resolved, it shows up at the answer. I'll fix.
