### ISSUE TITLE
Sidebar scrolling is broken

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#864]
Only able to scroll in [notebook](https://www.foretold.io/c/9ba34894-8fb7-40d8-b5c0-e7863ade924a/n/3c09353c-58aa-4758-ad0a-32c2d19522a4), not through measurables in sidebar.

![image](https://user-images.githubusercontent.com/21347592/69328277-418e0e80-0c4f-11ea-8f94-f04c2bde6cb6.png)

**Comment by OAGr** [comment]
Yep, this setup in general is kinda hacky, could be a decent amount of work to make nice.
