### ISSUE TITLE
Make default value of binary prediction slider "50%" [1.5, 1.7]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#877]
It currently start at 0%, which I've often found annoying. 

![image](https://user-images.githubusercontent.com/21347592/69802733-78799c80-11da-11ea-84f7-b2f25f4ead38.png)

Though I guess that might help with overconfidence, I think that's outweighed by it being a weird experience to new users.

**Comment by lagerros** [comment]
Another option is to have it start at the current aggregate. 

Bad: might cause anchoring. 
Good: mathematically elegant.

**Comment by OAGr** [comment]
Let's just do it at 50% for now.
