### ISSUE TITLE
When users are signed out, they should see a "Sign up" link as well as a "Log in" link.

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#939]
The "sign up" link should take them to the sign up page.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/95544e24-03ff-41e5-ba0d-87e9a702aa79)

### Sign in page:
![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/cb6d26fc-37ee-4744-957d-94def4cd8da7)

### Sign up page:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/377065/71579708-baf20a00-2af5-11ea-8697-8de75f1be32c.png">

**Comment by RomanGalochkin** [comment]
@OAGr "Sing up page" picture is broken.

**Comment by RomanGalochkin** [comment]
@OAGr

**Comment by OAGr** [comment]
Thanks, I'll look into fixing the image. I believe this issue is still possible to do though, even with a broken picture?

**Comment by RomanGalochkin** [comment]
I do not understand what should be shown on the sign-up page? Please describe with words.

**Comment by OAGr** [comment]
Oh, I see what you meant. I just meant the page that clicking "sign up" on the login page takes you to.

**Comment by RomanGalochkin** [comment]
Ok. Thanks.

**Comment by RomanGalochkin** [comment]
It seems that the "auth0-js" library does not have an opportunity to open a sign-up page directly only sign-in. At the moment will leave until the best time.
