### ISSUE TITLE
Notebooks don't show public questions that aren't in a user's communities

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#942]
There are some notebooks with links to questions that are in separate communities, but these questions are private. Users who are not in these communities cannot see these questions when viewing the notebooks, even though the questions are public. This seems like a filtering issue.

**Comment by RomanGalochkin** [comment]
Do we have an example of notebook?

**Comment by lagerros** [comment]
Try this: https://www.foretold.io/c/0d23ee60-c17b-4450-bc3f-049ce3d9d7fa/n/b3520920-927f-4c3f-9ff5-25dd0e7a758f 

Neither Roman nor Ozzie are in this community, so the measurables should look weird for you.

**Comment by OAGr** [comment]
Thanks!

**Comment by RomanGalochkin** [comment]
Do not see anything weird. Could anyone make a screenshot?

**Comment by lagerros** [comment]
Weird, it seems fine now!

**Comment by OAGr** [comment]
Strange, maybe one of the recent changes fixed it somehow.

**Comment by RomanGalochkin** [comment]
So, reopen please if new fact will be discovered.
