### ISSUE TITLE
It is a time to create the first simple integration test using GraphqlAPI

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#948]
The simplest form of test is the best what we need now:
1. To create a user.
2. To create a channel.
4. To create a measurable.
5. To make a prediction.

The environment should be already ready for this step.

**Comment by OAGr** [comment]
So to be clear, this would just be using the backend? If so, this seems pretty reasonable to me, feel free to prioritize accordingly.

**Comment by RomanGalochkin** [comment]
Yes, we do not need to write huge and super-deep unit tests. It is an integration test. 

So, some thoughts, steps to protect the application are:
1. We use types on the main client-side (ok).
2. We use graphql for intercommunication between clients over HTTP (ok).
3. On the server-side we using native JS without types (bad, much later we will need to migrate on **TypeScript** at least).
4. We use empty tests on the server-side to test imports (ok).
5. For the server-side we need to write unit tests (much later about 2030th).
6. We need to write some number of **integration tests** (on it).
7. We need tests for the client-side like snap-short tests (much later).
8. We use kit-components (ok).

**Comment by OAGr** [comment]
That generally sounds good to me. I guess Typescript would be fine for now; I was originally hoping we could wait out for ReasonML to be usable server side, but it seems like it's still not too great in that area. I imagine it would be relatively easy to start incorporating some Typescript into the app, though that would complicate the build system a bit.

**Comment by RomanGalochkin** [comment]
Each language has its own purpose. And ReasonML is not for the server-side. Differently. I think yes, but not so much as you think.
