### ISSUE TITLE
Guests cannot back to Home page from communities (no links)

### ISSUE THREAD

**Issue by RomanGalochkin** [foretold-app/foretold#955]
![Screenshot_20191230_131643](https://user-images.githubusercontent.com/16107421/71577796-a0745c80-2b06-11ea-82c5-e77ca00bca75.png)

![Screenshot_20191230_131750](https://user-images.githubusercontent.com/16107421/71577843-c994ed00-2b06-11ea-96bb-d0fe4ff77096.png)

**Comment by OAGr** [comment]
Good catch, will think about.

**Comment by OAGr** [comment]
I think at this point they can just click the logo.
