### ISSUE TITLE
Resolved questions send 40+ duplicate emails 

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#956]
From this community: https://www.foretold.io/c/5e947a59-64b9-458c-ba82-06e177fae4ea

![image](https://user-images.githubusercontent.com/21347592/71599769-852c4000-2b4c-11ea-807f-a23a8a59558f.png)

![image](https://user-images.githubusercontent.com/21347592/71599788-94ab8900-2b4c-11ea-8903-81970eb0f889.png)

**Comment by OAGr** [comment]
Gr.... thanks for bringing this up.

**Comment by RomanGalochkin** [comment]
Thanks.
