### ISSUE TITLE
Interpret user input "x to y" as "y to x" IF x > y, OR throw an error [3, 3]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#962]
One user made a prediction as "900 to 1". This is a bit unusual, but not that weird, and I can imagine others doing the same. 

I think this should either be interpreted as "1 to 900", or the user should be given an error message telling them to rearrange the numbers. 

This was labeled as "bug" rather than "enhancement" since at the moment this causes things to break. Consider for example this question with a min of 0:

![image](https://user-images.githubusercontent.com/21347592/71809308-22690600-3070-11ea-8178-a600a218ad5f.png)

**Comment by lagerros** [comment]
Hm, for some reason this does not seem to be a problem here: 

![image](https://user-images.githubusercontent.com/21347592/71965458-01cfb600-3200-11ea-9bb2-af446f08ef9f.png)

Maybe it's a smoothing issue?

**Comment by RomanGalochkin** [comment]
Will investigate.

**Comment by OAGr** [comment]
I want to delay this a bit more; will prioritize later. There's another version of this editor that's in development.

**Comment by OAGr** [comment]
I think it was never a unique problem, it was just a smoothing problem.
