### ISSUE TITLE
On "Communities" page, sort communities by number of members [4,3]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#964]
Communities with more members should be higher up on the page. 

Curated communities should show up on top, as referenced in #963 . But within the curated communities, we want to sort them by number of members.

**Comment by OAGr** [comment]
Note that:
1) Curated communities should be on the top.
2) Then, the curated and noncurated groups should be sorted based on number of members.

**Comment by OAGr** [comment]
I tried attempting this last week but it didn't quite work. I wouldn't recommend spending more than 2 hrs on it at this point.

**Comment by RomanGalochkin** [comment]
Ok, got it.
