### ISSUE TITLE
Show curated communities on top of "Communities" page [4,3] 

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#965]
Similar to what happens at the moment: ![image](https://user-images.githubusercontent.com/21347592/71986302-8a644b80-322c-11ea-93e8-8bdc1e67b6cc.png)

But making sure it is consistent with sorting communities by members, as mentioned in #964

**Comment by OAGr** [comment]
I don't get it, aren't the curated communities already on the top of the list?

**Comment by lagerros** [comment]
Yeah, but you asked me to submit two different issues for putting curated on top and sorting by number of members? I was assuming some work to make it compatible with sorting, and hence that it should have its own issue.

**Comment by OAGr** [comment]
I thought you meant something else; that you wanted the "curated" tag to be on curated communities when viewing those communities. This doesn't have to be a story if it's just "Do that other story, but don't break this existing functionality", essentially.

**Comment by lagerros** [comment]
Aha!
