### ISSUE TITLE
x-axis labels get jumbled for questions spanning larger intervals [3.2, 1.8]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#966]
For example: 
![image](https://user-images.githubusercontent.com/21347592/71989334-c51cb280-3231-11ea-969a-099e46202f5f.png)

From [this community](https://www.foretold.io/c/cf663021-f87f-4632-ad82-962d889a2d39?state=open). ([Link to question](https://www.foretold.io/c/cf663021-f87f-4632-ad82-962d889a2d39/m/072b7194-daa0-439b-8b83-acf18508c0aa))

**Comment by OAGr** [comment]
I think this is fixed at this point.
