### ISSUE TITLE
Don't round years [2, 1.5]

### ISSUE THREAD

**Issue by lagerros** [foretold-app/foretold#985]
The below is an x-axis showing years from 2020 to 2300. They shouldn't be rounded like that. 

![image](https://user-images.githubusercontent.com/21347592/72644900-1f242300-396a-11ea-83af-6315c13af6dd.png)

**Comment by OAGr** [comment]
We can't tell what a year is. Agreed this is not great, but it's not obvious how to fix, will need investigation.
